### ISSUE TITLE
How newpipe increase Live Window duraction of YouTube Live video.

### ISSUE THREAD

**Issue by SurajBahadur** [TeamNewPipe/NewPipeExtractor#1004]
If we play a live video of YouTube on android exoplayer by using hlsManifestUrl then the live window duration is of 30 seconds and In the new pipe library duration increases by 1 hour from 30 seconds. 

can anyone tell how the new pipe is modifying the duration?

**Comment by AudricV** [comment]
We use the HLS manifest of the iOS YouTube app, which returns live windows from 30 seconds up to 1 hour (`ANDROID` and `WEB` clients' ones are still used as a fallback if there is no manifest provided on the iOS client (this is unlikely to happen) or if the fetching of its player response fails). See #680 and #780 for more details.

Using the DASH manifest of YouTube, you should be able to have a live window which goes up to 4 hours, even if the first version of them is broken and pretty huge, that's the reason why it is not used.

However, I discovered recently that newer versions of these manifests are available, and can be get using a `mpd_version` parameter on the DASH manifest URL (the desktop website client uses the version 5, it goes up to version 7). This parameter should be added in the extractor soon.

By the way, that's NewPipe and not `new pipe`.

**Comment by SurajBahadur** [comment]
> We use the HLS manifest of the iOS YouTube app, which returns live windows from 30 seconds up to 1 hour (`ANDROID` and `WEB` clients' ones are still used as a fallback if there is no manifest provided on the iOS client (this is unlikely to happen) or if the fetching of its player response fails). See #680 and #780 for more details.
> 
> Using the DASH manifest of YouTube, you should be able to have a live window which goes up to 4 hours, even if the first version of them is broken and pretty huge, that's the reason why it is not used.
> 
> However, I discovered recently that newer versions of these manifests are available, and can be get using a `mpd_version` parameter on the DASH manifest URL (the desktop website client uses the version 5, it goes up to version 7). This parameter should be added in the extractor soon.
> 
> By the way, that's NewPipe and not `new pipe`.

Thank you @AudricV
