### ISSUE TITLE
[YouTube] ParsingException for hashtags links in descriptions and comments

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipeExtractor#1019]
See https://github.com/TeamPiped/Piped/issues/1967

`org.schabi.newpipe.extractor.exceptions.ParsingException: canonicalBaseUrl is null and browseId is not a channel ("{browseId=FEhashtag, params=6gUJCgdidW5uaWVz}")`

**Comment by AudricV** [comment]
Reopening, as the issue is not fixed: see TeamNewPipe/NewPipe#9774. I already found a way to fix the issue.
