### ISSUE TITLE
RegexException when trying to load YouTube decryption code

### ISSUE THREAD

**Issue by dankito** [TeamNewPipe/NewPipeExtractor#102]
A RegexException "failed to find pattern "(var SK=\{.+?\}\};)" occurs in YouTubeVideoStreamExtractor.loadDecryptionCode(String) in this line:

    helperObject = Parser.matchGroup1(helperPattern, playerCode);

I tried for example with this url: https://www.youtube.com/watch?v=fKFbnhcNnjE.

Affected NewPipe version is 0.11.5.

I'd like to post the value of playerCode variable here but this exceeds the allowed message length.
But I can send it to you in another way if you like to.

**Comment by theScrabi** [comment]
Please use the latest NewPipe version.

**Comment by theScrabi** [comment]
v0.14.0 works.

**Comment by dankito** [comment]
But there is no Version v0.14.0 on Jitpack.
The latest available version is v0.11.5.

Could you please add the v0.14.0 tag in Git and push it to GitHub, so that it gets available at Jitpack?
