### ISSUE TITLE
Can you add in a built in date year changer for newpipe app please.

### ISSUE THREAD

**Issue by KaineRecycler** [TeamNewPipe/NewPipeExtractor#1027]
hi there I want to submit a new feature request that allows newpipe users to relive older content from within youtube timeline so my new feature is a built in date year changer for the newpipe app for android so I want it to have a lock feature on the date year changer so that you can only browse the content that you are currently staying on and allow the date year changer to make changes to the newpipe app itself and for the lock and unlock feature when you want to change the date year so the lock feature will have a five digit pin number that you can sign in with your newpipe app account and when you are using it when you are signed out.

So this new feature for newpipe will allow to relive all past deleted unlisted private content based from within the youtube api timeline and allow this feature to also relive all videos channels and videos in all playlists based from created playlists to channel playlists that are found on the channel homepage and make newpipe app for android a better app for the android app market.

**Comment by AudricV** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/9815#issuecomment-1430310213

Don't spam the same request five times between multiple repos.
