### ISSUE TITLE
how should I configure the proguard-rule?

### ISSUE THREAD

**Issue by LuoMaoqiang** [TeamNewPipe/NewPipeExtractor#1048]
I did not find a description of how to configure proguard-rules in the documentation, how should I configure ?

**Comment by tarzancelmare** [comment]
Non riesco a trovare le estrazioni

**Comment by TobiGr** [comment]
See the proguard rules in NewPipe:
https://github.com/TeamNewPipe/NewPipe/blob/d845a158f0f8eb51e64c334cb42267f02202b29f/app/proguard-rules.pro#L6-L10
``` pro
## Rules for NewPipeExtractor
-keep class org.schabi.newpipe.extractor.timeago.patterns.** { *; }
-keep class org.mozilla.javascript.** { *; }
-keep class org.mozilla.classfile.ClassFileWriter
-dontwarn org.mozilla.javascript.tools.**
```
