### ISSUE TITLE
YouTube - Network Change Freezes Playback 

### ISSUE THREAD

**Issue by locuturus** [TeamNewPipe/NewPipeExtractor#1062]
Hello,

I'm guessing this is an extractor problem but if not then apologies in advance. 

The following applies to YouTube videos:
* If I start a video using mobile data and I later join WiFi then as soon as the mobile data video buffer runs out playback will freeze and will not recover. I must swipe NewPipe away from recents and open it again to resume.

* Alternatively if I start a video on WiFi and then switch to mobile data everything is okay. If I then rejoin WiFi it is still okay. I can switch networks as much as I like but only if the video begins on WiFi.

I don't know everyone's habits but I'm often on the move and frequently joining and leaving WiFi and so this is a huge annoyance. 

Tested on Pixel 4a, Android 13 beta; and Xperia 5 iii, Android 13. This issue is not new I'm only now getting around to submitting it.

<details><summary>Details from in-app error message</summary>
<p>
{"user_action":"play stream","request":"Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED] occurred while playing https://www.youtube.com/watch?v=mV8yM_I2_8Y","content_language":"en-US","content_country":"US","app_language":"en_US","service":"YouTube","package":"org.schabi.newpipe","version":"0.25.1","os":"Linux Android 13 - 33","time":"2023-05-14 19:56","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: Source error\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.UnknownHostException: Unable to resolve host \"rr1---sn-uhvcpax0n5-25xe.googlevideo.com\": No address associated with hostname\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)\n\tat com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)\n\tat com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)\n\tat com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)\n\tat com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)\n\tat com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)\n\tat java.lang.Thread.run(Thread.java:1012)\nCaused by: java.net.UnknownHostException: Unable to resolve host \"rr1---sn-uhvcpax0n5-25xe.googlevideo.com\": No address associated with hostname\n\tat java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)\n\tat java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)\n\tat java.net.InetAddress.getAllByName(InetAddress.java:1152)\n\tat com.android.okhttp.Dns$1.lookup(Dns.java:41)\n\tat com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)\n\tat com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)\n\tat com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)\n\tat com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)\n\tat com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)\n\tat com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)\n\tat com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)\n\tat com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)\n\tat com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)\n\tat com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)\n\t... 10 more\nCaused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)\n\tat libcore.io.Linux.android_getaddrinfo(Native Method)\n\tat libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)\n\tat libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)\n\tat libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)\n\tat java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)\n\t... 28 more\n"],"user_comment":""} 
</p>
</details>

**Comment by FireMasterK** [comment]
This has nothing to do with the extractor. You should look at the NewPipe repository.
