### ISSUE TITLE
Show Format File Size when extracting data

### ISSUE THREAD

**Issue by deniscerri** [TeamNewPipe/NewPipeExtractor#1064]
Coming from [Piped Repo](https://github.com/TeamPiped/Piped/issues/2429)
I am using the piped api which uses this extractor to get a list of formats for youtube videos.
Everything is ok, but the filesize data is missing.

I made that request there but it is not possible for them as the New Pipe Extractor needs to change.

**Comment by AudricV** [comment]
The info is already available for demuxed DASH streams which are progressive (the ones that aren't delivered by segments and use range requests), but Piped doesn't return it (`getContentLength` method of `ItagItem`s).

For muxed video streams, see #918. This can be applied to demuxed DASH progressive streams too.

For other streams, you will probably need to fetch the first sequences, extract metadata from the response and/or headers and do calculations using the bitrate and some metadata. Look at our DASH manifest creators for hints about where metadata is present.
