### ISSUE TITLE
[YouTube] New short date format

### ISSUE THREAD

**Issue by Theta-Dev** [TeamNewPipe/NewPipeExtractor#1067]
YouTube is A/B testing a new, shorter format for video upload dates.

The long format is still used for comments and playlist update dates.

### en-US

- Year: `y`
- Month: `mo`
- Week: `w`
- Day: `d`
- Hour: `h`
- Minute: `min`

### en-GB

- Year: `yr`
- Month: `mo`
- Week: `wk`
- Day: `day(s)`
- Hour: `hr`
- Minute: `min`

![image](https://github.com/TeamNewPipe/NewPipeExtractor/assets/19636565/ed184d0a-963e-4478-ace0-cfc09edbde1e)

The A/B test currently occurs very rarely (14 out of 1000 requests).

Here is a visitor data cookie for testing: `CgtJeFI1cWVSWVBTNCj6yc6jBg%3D%3D`

**Comment by AudricV** [comment]
I think it should occur in all languages.

## fr

- Year: `a`;
- Month: `m.`;
- Week: `sem.`;
- Day: `d`;
- Hour: `h`;
- Minutes: `min`.

**Comment by Theta-Dev** [comment]
Yes, it does. I have just written down the English versions.

BTW: YouTube most likely uses the Unicode CLDR repository for their date strings.

https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-dates-full/main/en-GB/dateFields.json

Here are the relevant keys:

Long version: `<unit>.relativeTime-type-past`

Short version: `<unit>-short.relativeTime-type-past`

So if we want to reimplement multi-language extraction, we can just extract the data from there and dont need to fetch samples from YouTube.

**Comment by wb9688** [comment]
It seems like YouTube is actually using the narrow version for this, not the short version.
