### ISSUE TITLE
[SoundCloud] CI blocked from fetching website

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipeExtractor#1079]
CI fails, because SoundCloud client id cannot be extracted:
`Could not resolve id with embedded player. ClientId not extracted`
For more logs, see https://github.com/TeamNewPipe/NewPipeExtractor/actions/runs/5428294717/jobs/9872362514#step:5:155
Expected response while parsing the embedded player HTML is a valid page containing some JS scripts. **We get a 403 instead**

<details><summary>embedded player response (HTML)</summary>

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 06WG1ZEymv9v-Ws2SenAVCA5vaMLwvrd3foEi8aL0pXyWGL4Ed-kOA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```
</details>

It looks like SoundCloud has blacklisted many servers and refuses to serve content to them. This includes GitHub Actions, but also VPN exit nodes...
To fix the tests, we might need to create mocks, too, and setup a server to run the daily tests.

**Comment by AudricV** [comment]
SoundCloud reverted this change since a few weeks and the CI is able to get data from the service again. Closing as fixed.
