### ISSUE TITLE
Update params for fetching stream data?

### ISSUE THREAD

**Issue by ChunkyProgrammer** [TeamNewPipe/NewPipeExtractor#1115]
I think the player params may need to be updated in NewPipeExtractor.

Looks like NewPipeExtractor is using the params  `CgIQBg`:
https://github.com/TeamNewPipe/NewPipeExtractor/blob/f9846352ea85f708e93828ead66159313d79973d/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L946

Invidious and Youtube.js seem to be switching to/using `2AMBCgIQBg` instead:
see: 
https://github.com/LuanRT/YouTube.js/blob/e54c0c4bf16c20e431fde91d1ced39d34999e27f/src/core/endpoints/PlayerEndpoint.ts#L46
and
https://github.com/iv-org/invidious/pull/4156

**Comment by AudricV** [comment]
No, we won't change them, as `2AMB` is used to bypass throttling on adaptive streaming URLs and could be used as an easy way to detect third-party clients.

YouTube ReVanced uses the same parameters as us and it doesn't have any throttling issue.

Closing as won't fix.
