### ISSUE TITLE
Call requires API level 33 (current min is 26): java.util.stream.Collectors#toUnmodifiableList

### ISSUE THREAD

**Issue by polopai** [TeamNewPipe/NewPipeExtractor#1120]
https://github.com/TeamNewPipe/NewPipeExtractor/blame/eac850ca1077c7615d8b211502f346eb5e2284b0/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java#L1192

Hello, in the submitted update a few months ago, this method "java.util.stream.Collectors#toUnmodifiableList" was used in many places, (Call requires API level 33 (current min is 26): java.util. stream.Collectors#toUnmodifiableList).
Actual testing shows that this method cannot be found on phones lower than Android 13, resulting in failure.

**Comment by AudricV** [comment]
From the project README:

> Note: To use NewPipe Extractor in Android projects with a `minSdk` below 26, [API desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) is required. If the minSdk is below 19, the `desugar_jdk_libs_nio` artifact is required, which requires Android Gradle Plugin (AGP) version 7.4.0.

This method is embedded in Android API desugaring, see https://developer.android.com/studio/write/java11-default-support-table.

Closing as invalid.
