### ISSUE TITLE
Support other item types in ListInfo related items

### ISSUE THREAD

**Issue by migalmoreno** [TeamNewPipe/NewPipeExtractor#1121]
I've recently gotten a [feature request](https://github.com/migalmoreno/tubo/issues/1) which asks for support for playlists in channel pages but AFAICT related items for `ChannelInfo` (and `ListInfo` consequently) only return stream types. Is there any plan for eventually supporting more item types?

**Comment by AudricV** [comment]
This is already supported: see changes of #1082. Please look (better?) at existing issues and pull requests before opening a new issue in the future. Thank you.

**Comment by migalmoreno** [comment]
Thanks for the pointer! I completely overlooked that PR
