### ISSUE TITLE
YouTube Parse Error

### ISSUE THREAD

**Issue by Git-Forked** [TeamNewPipe/NewPipeExtractor#1136]
Extractor reports a parse error for YouTube. 
YouTube has probably changed something again that requires an update to the extractor. 
All the other media sites still load content. 
Thank you to whoever can look into this and resolve it.

**Comment by AudricV** [comment]
Please give more details about the issue, especially where and on what it occurs, there is nothing we can do to investigate it with the info you gave.

**Comment by Git-Forked** [comment]
My apologies. 
I was able to resolve the issue. 
It seems after much more investigation that the cause of the issue was not NewPipeExtractor. 
I found the issue was in DNScrypt, and that it was blocking a required URL that NewPipe needed, even though previously this had never been the issue before with using DNScrypt and NewPipe.
