### ISSUE TITLE
**FEATURE REQUEST**Video Lock When Scrolling - Similar to Odysee & YouTube**

### ISSUE THREAD

**Issue by DecodeRecode** [TeamNewPipe/NewPipeExtractor#1161]
There is a feature that I have noticed that YouTube, and Odysee (Lbry) have when you play their videos. The feature is locking the video that is playing while scrolling through the comments. At the moment, New Pipe is awesome, but when I scroll down to the comments or the video library under the current video, the video goes out of view when I scroll. If I won't to see what is going on in the video, I have to scroll up to bring it into view. I appreciate your work. I think this would be an awesome feature to have.

**Comment by AudricV** [comment]
Invalid repository, this feature has been already requested on the correct repository (TeamNewPipe/NewPipe).
