### ISSUE TITLE
Wrong view count gets extracted

### ISSUE THREAD

**Issue by MaX-Lo** [TeamNewPipe/NewPipeExtractor#117]
This issue exists already in NewPipe (https://github.com/TeamNewPipe/NewPipe/issues/1714) but since it's more an issue in the extractor for the Youtube service I created it here too.

On some videos youtube places "Recommended for you" instead of e.g. "188K views" so the newpipe extractor semms not to know what to do with that and returns 0 views.

**Comment by theScrabi** [comment]
I see. But there is still a views field on those "recommended for you" videos?

**Comment by theScrabi** [comment]
I see, but the viws are not displayed anymore.

**Comment by TobiGr** [comment]
> `<span id="video-title" class="style-scope ytd-compact-video-renderer" aria-label="MTB WHEEL OF FORTUNE - EP 2 - DIRT AND ENDURO CHALLENGE by Sam Pilgrim 2 days ago 14 minutes 35,653 views" title="MTB WHEEL OF FORTUNE - EP 2 - DIRT AND ENDURO CHALLENGE"> MTB WHEEL OF FORTUNE - EP 2 - DIRT AND ENDURO CHALLENGE </span>`

Maybe we can just extract the last number of the `aria-label` attribute with a regex like `([\d\.,]+)\D*$`. Then we just have to take the first group.

**Comment by wb9688** [comment]
Hmm… on yt_new I wasn't able to find where YouTube puts them now, if they even still provide it.

**Comment by AudricV** [comment]
The extractor returns `-1` when the text `recommended` is present and when it cannot be parsed. See [`YoutubeStreamInfoItemExtractor.getViewCount()`](https://github.com/TeamNewPipe/NewPipeExtractor/blob/d961d349c35c93c53ae419935d93fa4533fe71ca/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemExtractor.java#L288-L341) for more details.

Closing as fixed.
