### ISSUE TITLE
Throttling parameter extraction fails

### ISSUE THREAD

**Issue by Theta-Dev** [TeamNewPipe/NewPipeExtractor#1190]
YouTube changed their code to make it more difficult to extract the throttling parameter decryption function. Specifically they used `String.fromCharCode(110)` as a substitute for `"n"`.

Working: https://www.youtube.com/s/player/5352eb4f/player_ias.vflset/en_US/base.js
```js
a.D&&(b=a.get("n"))&&(b=FRa[0](b),a.set("n",b),FRa.length||Fma(""))}};
```

New: https://www.youtube.com/s/player/b22ef6e7/player_ias.vflset/de_DE/base.js
```js
a.D&&(b=String.fromCharCode(110),c=a.get(b))&&(c=IRa[0](c),a.set(b,c),IRa.length||Ima(""))}};
```

Edit: YouTube now returns 403 if a stream is requested without the deobfuscated n parameter. So this is probably the cause for https://github.com/TeamNewPipe/NewPipe/issues/11255

**Comment by Stypox** [comment]
Fixed by #1191
