### ISSUE TITLE
Can't pull HD

### ISSUE THREAD

**Issue by jhabdas** [TeamNewPipe/NewPipeExtractor#120]
C4 Pedro - Tu És a Mulher

Want to download it. But let's be honest anything less that 720p video/audio combo sucks. How can this be Improved so the app can survive?

**Comment by theScrabi** [comment]
> But let's be honest anything less that 720p video/audio combo sucks.

Do you mean there is no audio/viode streams? If so, that is an issue of youtube, because they ged delivered in different streams. We are currently discussing about a download postprocessor for muxing.

**Comment by jhabdas** [comment]
Ah okay. I didn't realize a muxer wasn't already integrated. Seems necessary. Closing.
