### ISSUE TITLE
how to change package name without error 

### ISSUE THREAD

**Issue by muzahid2018** [TeamNewPipe/NewPipeExtractor#125]
i am new in java and Android Studio,  i want to modify newpipe app ,but when i try to change package name i get error about Extractor component . i fixed it buy downloading and adding extractor folder on the folder, but i get another error related to subtitles.java  its not in extractor folder, 
i hope you understand the issue .

please tell me which file i need to modify or edit to rename the package.

**Comment by theScrabi** [comment]
You may not need to change any package name.

**Comment by PeterHindes** [comment]
Usually in a large project like this, the best way to rename it is with a global find and replace. Even then you may still have issues. It would help to know why you need to rename it.

**Comment by AudricV** [comment]
Closing due to lack of author's response.
