### ISSUE TITLE
NewPipe does not support 251 itag opus format

### ISSUE THREAD

**Issue by Figim** [TeamNewPipe/NewPipeExtractor#1251]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipeExtractor/releases/latest).
- [X] I am aware that this issue is being opened for the NewPipe Extractor, NOT the [app](https://github.com/TeamNewPipe/NewPipe), and my bug report will be dismissed otherwise.
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipeExtractor/issues) or [closed](https://github.com/TeamNewPipe/NewPipeExtractor/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.3

### Steps to reproduce the bug

1. https://youtu.be/uu08O94L13k
2. **Watch this video on LibreTube. Close Piped proxy
3. You need to activate DASH.**
4. Go to the "Stats for Nerds" section

5. 
![Screenshot_20241223-120208_LibreTube Debug](https://github.com/user-attachments/assets/d5f3da66-dca9-4551-b8ae-e32b6f4c04f1)

**But play this video on YouTube. I don't have a premium account and I can play it in 251 Opus format.**

![Screenshot_20241223-115110_YouTube](https://github.com/user-attachments/assets/17229c78-2be7-4e48-a168-33f5448f562b)

### Expected behavior

Support for 251 opus audio formats

### Actual behavior

NewPipe does not support 251 opus formats like YouTube with Ads

### Screenshots/Screen recordings

Ytdlp supports this as well

![Screenshot_20241223-120840](https://github.com/user-attachments/assets/9b7fbc3e-2572-414f-af0f-16ee54f146ed)

### Logs

There is information above.

### Additional information

No

**Comment by AudricV** [comment]
Both the extractor (otherwise you won't be able to get it in LibreTube without Piped proxy, as it uses the extractor) and the app does. You're mismatching itag IDs with their bitrate.

**Comment by AudricV** [comment]
Read again my comment:

> You're mismatching itag IDs with their bitrate.

251 is the internal stream ID (itag) from YouTube, 160 kbps is an average value used by NewPipe from the average bitrate returned by YouTube. Look at the code [here](https://github.com/TeamNewPipe/NewPipeExtractor/blob/8e92227b2e6de08fe27e5efca443c8cad1292e78/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/ItagItem.java#L61).

From your screenshot you provided of the video you used in LibreTube (`puu08O94L13k`), the itag 251 in this video has a real average bitrate of 140 kbps.
