### ISSUE TITLE
Errors when extracting audio

### ISSUE THREAD

**Issue by NitroNils** [TeamNewPipe/NewPipeExtractor#150]
Cannot extract audio in the current and last version from F-Droid (0.16.1)

This error on .mp3 attempt:
```
Code: 1007
Post-processing failed

java.lang.RuntimeException: stopped unexpectedly
```
And this on .opus:
`HTTP 403`
Video streams normally.

So I have a pile of files cluttering my 'Downloads' area.
Could this be OS-related?

Android 6
Huawei P8 Lite

android:versionCode="730" android:versionName="0.16.1" android:compileSdkVersion="28" android:compileSdkVersionCodename="9" package="org.schabi.newpipe" platformBuildVersionCode="730" platformBuildVersionName="0.16.1">
<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28"/>

**Comment by kapodamy** [comment]
Post-processing in mp3 files??? what video are you trying to download?
"stopped unexpectedly" occurs if the app is closed while the muxer is running

**Comment by NitroNils** [comment]
Well, it' been failing both video and audio postprocessing. All audio and seemingly non-default  formats (from the selection of formats).
Lastly [this video](https://www.youtube.com/watch?v=7t6iOag6kcE) in mp4 @ 480p.

**Comment by NitroNils** [comment]
Also 16.2.
Now I read more people are reporting muxing issues.

**Comment by TiA4f8R** [comment]
This issue is really outdated and is not really related to the extractor. Closing.

If you are still getting 403s, please let us know.

Thank you!
