### ISSUE TITLE
'Show info' does not show info.

### ISSUE THREAD

**Issue by NitroNils** [TeamNewPipe/NewPipeExtractor#151]
'Show info' does not show info but loads the video directly.
From all places where it appears (ie. from Downloads context menu, from What's new, etc.).

This is destructive when one has a limited dataplan.

Android 6
Huawei P8 Lite
```
android:versionCode="730" android:versionName="0.16.1" android:compileSdkVersion="28" android:compileSdkVersionCodename="9" package="org.schabi.newpipe" platformBuildVersionCode="730" platformBuildVersionName="0.16.1">
<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28"/>
```

**Comment by theScrabi** [comment]
I don't think this issue belongs into the android extractor. Because here we only focus on the extractor code.

With show info you mean the show info in the frontend? Then please open this issue in the frontend.

**Comment by NitroNils** [comment]
My bad.
Yes, front-end.
Will do!
Thanks.
