### ISSUE TITLE
Extractor Down Again

### ISSUE THREAD

**Issue by razorshiv** [TeamNewPipe/NewPipeExtractor#153]
Youtube is on the move again. Extractor decryption error on all videos.

**Comment by maltfield** [comment]
Note this is also broken in v0.14.1, which used to work until today.

**Comment by ouzowtf** [comment]
You should use an up-to-date version of NewPipe (0.16.1)

**Comment by gitrdn** [comment]
In F-Droid, 0.16.1 is not listed and 0.14.1 returns "file not found" error.

**Comment by theScrabi** [comment]
This is an fdroid issur. The client has issues with caching. You may want to remove and reinstall fdroid.

**Comment by gitrdn** [comment]
Newpipe is now working again, THANK YOU GUYS.  Also, thanks for the F-Droid tip, will try reinstalling F-Droid.

**Comment by razorshiv** [comment]
I just realized there is a "new new" NewPipe Legacy app and version. :/ It is working. Did I miss the memo on this? Does anyone have that memo?

**Comment by razorshiv** [comment]
Never mind, I've got to finish my TPS reports.

**Comment by maltfield** [comment]
Confirmed that updating my F-Droid repos shows 0.16.1, and upgrading to it fixed this issue.

For some reason, the latest change-log-entry in my F-Droid app for newpipe apply to 0.15.1, and that's the "Suggested" version.

That differs from the latest change-log-entry on the F-Droid website, which clearly shows 0.16.1 fixes the decrypt function error:

 * https://f-droid.org/en/packages/org.schabi.newpipe/

**Comment by TobiGr** [comment]
> For some reason, the latest change-log-entry in my F-Droid app for newpipe apply to 0.15.1, and that's the "Suggested" version.

That's odd, I took a look at [F-Droid Data](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.schabi.newpipe.yml) and the entry shows following:
```
CurrentVersion: 0.16.1
CurrentVersionCode: 730
```
This seems to be a F-Droid bug.

Nevertheless, it looks like YouTube reverted the changes to their website, so we're save to close this
