### ISSUE TITLE
[Suggestion] Add bitchute support

### ISSUE THREAD

**Issue by dankxylese** [TeamNewPipe/NewPipeExtractor#157]
I know that it will take a lot of time and effort to build in a webTorrent client to NewPipe, but maybe you could use youtube-dl and their implementation to help with this. https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/bitchute.py

Its a new platform and a few people I follow have moved there but its a lot harder to watch their content through a web browser as opposed to NewPipe

**Comment by connectety** [comment]
there was a [PR](https://github.com/TeamNewPipe/NewPipe/pull/2131) which tried to utilize youtube-dl.
It got dismissed for a number of reasons: https://github.com/TeamNewPipe/NewPipe/pull/2131#issuecomment-465487337

**Comment by ijurisic** [comment]
I will love to see support for Bitchute in NewPipe

**Comment by Stypox** [comment]
Closing in favour of #320
