### ISSUE TITLE
Testing and decouple extractor

### ISSUE THREAD

**Issue by mauriciocolli** [TeamNewPipe/NewPipeExtractor#16]
As @TheAssassin said [here](https://github.com/TeamNewPipe/NewPipeExtractor/pull/15#issuecomment-319029514), I want to see the tests working too.

I'm thinking in doing this:
- Move the unit tests to here
- Make this repository "buildable" with gradle
- Use [jitpack.io](https://jitpack.io) to import it to NewPipe as a dependency (I think that @theScrabi said that he wanted to include in maven right? For now, jitpack will be enough)

Currently, doesn't make much sense having the tests there, a big reason is:
- For each commit that is done there, the unit tests start **ALL** again testing this repository **that remains intact**, we are just repeating the tests without changing anything

Another reason would be that is easier to modify the extractor or include in another project, as it'll be a totally independent module, for now, it is a little bit coupled with NewPipe repository...

What do you guys think? If you have suggestions, feel free to let me know.

**Comment by wb9688** [comment]
Well, I was thinking about doing the same thing after my PR is merged. I'll
also have to write unit tests for my service.

**Comment by wb9688** [comment]
@mauriciocolli: The tests depends on [`Downloader.java`](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/Downloader.java), what should I do with that?

**Comment by theScrabi** [comment]
@mauriciocolli 
> I think that @theScrabi said that he wanted to include in maven right? For now, jitpack will be enough
Yes that was the idea to also put the backed into a maven repo.
jitpack.io is nice :)
