### ISSUE TITLE
Keep Updated?

### ISSUE THREAD

**Issue by darkdoctor** [TeamNewPipe/NewPipeExtractor#169]
Hi.

Great library.

I wonder how can I know always which one is the last version. In NewPipe app, I see some ID's instead of version number.

BR

**Comment by theScrabi** [comment]
The last stable version should always be the one on the master branch, as well as the latest tag. However I wonder. The latest tags are missing :/

**Comment by TiA4f8R** [comment]
Because the extractor releases are now detached to the ones of the app, a part of the previous comment may not apply.

We are sometimes using extractor versions from a specific commit directly in the app, and not a release version itself.

Closing as answered.
