### ISSUE TITLE
Can add NewPipeExtractor as a dependency in maven project?

### ISSUE THREAD

**Issue by w3y** [TeamNewPipe/NewPipeExtractor#171]
Hi,
I want to build a service using NewPipeExtractor as a path of this project. I'm using Spring framework and maven, so can I add NewPipeExtractor as a dependency?
Like this:
```
       <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
```
```
       <dependency>
            <groupId>com.github.TeamNewPipe</groupId>
            <artifactId>NewPipeExtractor</artifactId>
            <version>v0.16.2</version>
        </dependency>
```
I'm getting an error that ` Failure to find com.github.TeamNewPipe:NewPipeExtractor:jar:v0.16.2 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced
`
Pls help me!

**Comment by theScrabi** [comment]
Then instead of the tag use the commit id,
maybe that helps you more:
```
<dependency>
	    <groupId>com.github.TeamNewPipe.NewPipeExtractor</groupId>
	    <artifactId>NewPipeExtractor</artifactId>
	    <version>4c633c2166</version>
</dependency>
```
However to me it looks like you did everything right.

**Comment by w3y** [comment]
@theScrabi Thanks for helping. I have been added to my project sucessfuly. So, Is v0.16.2 stable version?
