### ISSUE TITLE
Youtube channel-filtered search also provides some videos

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipeExtractor#178]
Try [this channel filtered search](https://www.youtube.com/results?search_query=pewdiepie&sp=EgIQAg%253D%253D). As you can see youtube provides only channels, except 3 "important" PewDiePie videos at the top. This causes `YoutubeSearchExtractorChannelOnlyTest.testOnlyContainChannels()` to fail. Here are two ways it could be solved in `YoutubeSearchExtractor.getPage()`:
- Remove all videos from the extracted items and only keep channels. It *may* impose some overhead.
- Keep everything and edit/remove `testOnlyContainChannels()`. This keeps consistency with YouTube (in case they ever change something again) and does not create many problems: as I said above the number of unexpected videos is only 3...

I'd go with the second option. Let me know your opinion, then I'll open a pr :-)

**Comment by wb9688** [comment]
Doesn't happen with yt_new at least. That's because those videos from a channel have a different type of renderer, which we just ignore.
