### ISSUE TITLE
how can i get/extract youtube audio stream link of any video

### ISSUE THREAD

**Issue by waqarr** [TeamNewPipe/NewPipeExtractor#181]
how can i get/extract youtube audio m4a stream link of any video with new pipe extractor?

**Comment by kapodamy** [comment]
```java
String url = "https://www.youtube.com/watch?v=OYVDpdMWopQ";
NewPipe.init(Downloader.getInstance(), new Localization("AR", "es"));
YoutubeStreamExtractor extractor = ServiceList.YouTube.getStreamExtractor(url);
extractor.fetchPage();

for (AudioStream a : extractor.getAudioStreams()) {
    if (a.getFormat() == MediaFormat.M4A) {
        System.out.println("url: " + a.getUrl());      
    }
}
```

**Comment by waqarr** [comment]
REally sorry for delay. i got this error

error: cannot find symbol
    NewPipe.init(Downloader.getInstance(), new Localization("EN", "us"));
                           ^
  symbol:   method getInstance()
  location: class Downloader

how can i resolve this issue. 

Really thank you so much for this help. May you live long.

**Comment by wb9688** [comment]
@waqarr: You have to provide your own implementation of `Downloader`, see `DownloaderImpl` in NewPipe or in NewPipeExtractor's tests for an example.

**Comment by waqarr** [comment]
Problem Now: cannot fetch audio stream link exception "null "


I'm Using this code 

try {
            String url = "https://www.youtube.com/watch?v=ZTBwxy4wsBQ";
            NewPipe.init(getDownloader(), new Localization("EN", "us"));
            YoutubeStreamExtractor extractor = (YoutubeStreamExtractor) ServiceList.YouTube.getStreamExtractor(url);
            extractor.fetchPage();

            for (AudioStream a : extractor.getAudioStreams()) {
                if (a.getFormat() == MediaFormat.M4A) {
                    //System.out.println("url: " + a.getUrl());
                    Log.d("urlAudio: ", a.getUrl());
                }
            }
        } catch (Exception e){
                Log.d("urlException", ""+e.getMessage());
        }






-----------------------------------

define function same activity 



protected Downloader getDownloader() {
        DownloaderImpl downloader = DownloaderImpl.init(null);
        setCookiesToDownloader(downloader);
        return downloader;
    }

    protected void setCookiesToDownloader(final DownloaderImpl downloader) {
        final SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(
                getApplicationContext());
        final String key = "recaptcha_cookies_key";
        downloader.setCookie(ReCaptchaActivity.RECAPTCHA_COOKIES_KEY, prefs.getString(key, ""));
        downloader.updateYoutubeRestrictedModeCookies(getApplicationContext());
    }




------------------------------------

Import Files 

ReCaptchaActivity
DownloaderImpl
InfoCache
CookieUtils
TLSSocketFactoryCompat

**Comment by waqarr** [comment]
Everything is working now. DownloaderImp.java file issue. 

Thank you so much all
