### ISSUE TITLE
Preload buffering more than one music.

### ISSUE THREAD

**Issue by lextonn** [TeamNewPipe/NewPipeExtractor#203]
Hello,
Is it possible to add preload tracks playing in the background?
Something like in Subsonic app for android where you can set how many tracks can be preload and how much size can be buffored. It will be very helpful when someone drive and listenning music from NewPipe and sometimes don't have enough signal in phone or modem and music stops.
Regards

**Comment by hardBSDk** [comment]
Curious question, I would like to say another question:
do NewPipe cache the entire sound stream or only chunks of it?

**Comment by TiA4f8R** [comment]
This is a NewPipe feature request, which is really old, and not an extractor request. Please check if your feature has been requested on the NewPipe repository instead of the extractor one. Thank you!
