### ISSUE TITLE
SoundCloud broken

### ISSUE THREAD

**Issue by ToothlessNEO** [TeamNewPipe/NewPipeExtractor#205]
Whenever I open the SoundCloud tab it says no videos and crashes and afterwards It won't load YouTube or MediaCCC

**Comment by theScrabi** [comment]
I as well noticed some issues with soundcloud.

**Comment by TobiGr** [comment]
The `client_id` has been moved to a new file. in my case https://a-v2.sndcdn.com/assets/11-63afa89b-3.js The question is whether that url and page are generated dynamically or not. Can someone else confirm when viewing the source code of https://soundcloud.com the find the link above?

**Comment by axel2230** [comment]
> The `client_id` has been moved to a new file. in my case https://a-v2.sndcdn.com/assets/11-63afa89b-3.js The question is whether that url and page are generated dynamically or not. Can someone else confirm when viewing the source code of https://soundcloud.com the find the link above?
> In my case that file is horrible 0,8 MB large.

The file exists but a quick search shows no mention of `client_id` on that specific file.
In my case, `client_id` is defined here https://a-v2.sndcdn.com/assets/47-e78af4bc-3.js

**Comment by TobiGr** [comment]
Thtanks, @axel2230.
I found out, that the client_id is still included in `m.soundlcoud.com`, we used `soundlcoud.com` before. I'll try to use and parse the mobile version instead.

**Comment by axel2230** [comment]
> Thtanks, @axel2230.
> I found out, that the client_id is still included in `m.soundlcoud.com`, we used `soundlcoud.com` before. I'll try to use and parse the mobile version instead.

Can confirm `client_id` is present on `m.soundcloud.com`. Let's hope it stays that way for the foreseeable future.

**Comment by TobiGr** [comment]
PR is open, nevertheless it increases the downloaded file size many times over. To compare: before it was ~20kb, now we have ~1.8MB.
That's why, I'd like to identify the correct script to download. @axel2230 Maybe, we can find a pattern. Which scripts do you see? That are mine (the correct one was the first):
``` HTML
<script src="https://a-v2.sndcdn.com/assets/11-63afa89b-3.js" crossorigin></script>
<script type="text/javascript">window.__sc_version = "1571658479";</script>
<script crossorigin src="https://a-v2.sndcdn.com/assets/49-3251d2aa-3.js"></script>
<script crossorigin src="https://a-v2.sndcdn.com/assets/0-a57f9900-3.js"></script>
<script crossorigin src="https://a-v2.sndcdn.com/assets/1-b6b1d6d3-3.js"></script>
<script crossorigin src="https://a-v2.sndcdn.com/assets/50-3c8821ad-3.js"></script>
<script crossorigin src="https://a-v2.sndcdn.com/assets/48-d810964b-3.js"></script>
<script crossorigin src="https://a-v2.sndcdn.com/assets/47-e78af4bc-3.js"></script>
```

**Comment by TobiGr** [comment]
Further testing with VPN and different devices gave me the same client_id the whole time. Can someone confirm that? (`NTMpakZ*********5luouSrAuVZv`)

**Comment by axel2230** [comment]
> PR is open, nevertheless it increases the downloaded file size many times over. To compare: before it was ~20kb, now we have ~1.8MB.
> That's why, I'd like to identify the correct script to download. @axel2230 Maybe, we can find a pattern. Which scripts do you see? That are mine (the correct one was the first):
> 
> ```
> <script src="https://a-v2.sndcdn.com/assets/11-63afa89b-3.js" crossorigin></script>
> <script type="text/javascript">window.__sc_version = "1571658479";</script>
> <script crossorigin src="https://a-v2.sndcdn.com/assets/49-3251d2aa-3.js"></script>
> <script crossorigin src="https://a-v2.sndcdn.com/assets/0-a57f9900-3.js"></script>
> <script crossorigin src="https://a-v2.sndcdn.com/assets/1-b6b1d6d3-3.js"></script>
> <script crossorigin src="https://a-v2.sndcdn.com/assets/50-3c8821ad-3.js"></script>
> <script crossorigin src="https://a-v2.sndcdn.com/assets/48-d810964b-3.js"></script>
> <script crossorigin src="https://a-v2.sndcdn.com/assets/47-e78af4bc-3.js"></script>
> ```

I'll gladly help, 1.8MB here and there would make the app way to slow.

This is what I get:
```
<script src="https://a-v2.sndcdn.com/assets/11-63afa89b-3.js" crossorigin=""></script>
<script type="text/javascript">window.__sc_version = "1571658479";</script>
<script crossorigin="" src="https://a-v2.sndcdn.com/assets/49-3251d2aa-3.js"></script>
<script crossorigin="" src="https://a-v2.sndcdn.com/assets/0-a57f9900-3.js"></script>
<script crossorigin="" src="https://a-v2.sndcdn.com/assets/1-b6b1d6d3-3.js"></script>
<script crossorigin="" src="https://a-v2.sndcdn.com/assets/50-3c8821ad-3.js"></script>
<script crossorigin="" src="https://a-v2.sndcdn.com/assets/48-d810964b-3.js"></script>
<script crossorigin="" src="https://a-v2.sndcdn.com/assets/47-e78af4bc-3.js"></script>
```

`client_id` is defined at `<script crossorigin="" src="https://a-v2.sndcdn.com/assets/47-e78af4bc-3.js"></script>`

This looks troublesome. The script ids are the same but the contents are stored at random under these ids.

**Comment by axel2230** [comment]
> Further testing with VPN and different devices gave me the same client_id the whole time. Can someone confirm that? (`NTMpakZ*********5luouSrAuVZv`)

Bingo
`client_id: "NTMpakZL0VZhMPAHJvVX5luouSrAuVZv"`
@TobiGr do you get the same id?

**Comment by TobiGr** [comment]
Yes

**Comment by axel2230** [comment]
Will do a few more tests on a VPN Connection

**Comment by TobiGr** [comment]
Btw. the client_id is only fetched once when the soundcloud service is initialized.

**Comment by axel2230** [comment]
> Btw. the client_id is only fetched once when the soundcloud service is initialized.

I'm not sure if I'm following correctly but:
1. I am using a new incognito window for each VPN Session to clear cookies and anything else like that.
2. Changing VPN exit points. 

So far US, Mexico, Canada and Japan show the same id at `<script crossorigin="" src="https://a-v2.sndcdn.com/assets/47-e78af4bc-3.js"></script>`

I don't know if the id will change over time but I definitely find it weird that your id is defined on another script.

**Comment by TobiGr** [comment]
@axel2230 Thanks! I corrected my comment above some time ago, I also get the id from https://a-v2.sndcdn.com/assets/47-e78af4bc-3.js. Sorry I should have corrected this in a new comment instead of editing some info.
I'll wait for @theScrabi's, @mauriciocolli's and @Stypox's opinion on this. But I guess we can build a nice algo around this which can even reduce the downloaded stream.

**Comment by axel2230** [comment]
> @axel2230 Thanks! I corrected my comment above some time ago, I also get the id from https://a-v2.sndcdn.com/assets/47-e78af4bc-3.js. Sorry I should have corrected this in a new comment instead of editing some info.
> I'll wait for @theScrabi's, @mauriciocolli's and @Stypox's opinion on this. But I guess we can build a nice algo around this which can even reduce the downloaded stream.

No worries.
Yeah I saw your comment on the PR downloading less than half the file is a clever idea.

**Comment by mauriciocolli** [comment]
Keep in mind that we were already downloading only the first 16KB of that file, take at look at this commit: 1c8dafe4c673453712f893f8b2577aff06f0499d.

Nevertheless, this are my findings regarding this:
 
- The client id seems to be regenerated at the 3-4 months mark, according to the history of this line on the `youtube-dl` project (they hardcode it): [extractor/soundcloud.py#L224](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/soundcloud.py#L224)
- They use two ids that stay the same and are valid until they change: one for the normal site and one for the mobile, which aren't interchangeable.
- I did notice a pattern in these new separated scripts: the order which they appear matches with their `Last-Modified` header. And considering the fact that they keep their ids and setup variables in the same place, I'd say the probability of the right one appear at the bottom whenever they change it is high.

We _could_ use the `youtube-dl`'s method (hardcoding), but then we'd have to update every time it changes.

IMO, I say we continue doing this way but with one improvement: cache the client id for some amount of time, which will be set taking in consideration the rate which it's updating. What do you guys think?

I've pushed a commit, without caching for now, so you all can take a look: 860b4f2a44a1a35f5c64b7f2c41a529f07b861c1, (@TobiGr if you want I can push it to that fix branch).

**Comment by TobiGr** [comment]
@mauriciocolli 860b4f2a44a1a35f5c64b7f2c41a529f07b861c1 looks good. The only question is whether we want to keep the old (not working)  parser as a fallback in case something changes again.

> Cache the client id for some amount of time, which will be set taking in consideration the rate which it's updating.

Yes, I forgot that. :)

> The client id seems to be regenerated at the 3-4 months mark,

We could also provide it via the [API](https://newpipe.schabi.org/api/data.json) which is updated every hour. @TheAssassin What do you think? As long as the API is not reliable enough, we can fallback to the method in 860b4f2a44a1a35f5c64b7f2c41a529f07b861c1.

**Comment by kapodamy** [comment]
I propose the following:
1_ download the desktop homepage
2_ read all **external** scripts in html body (aka `document.querySelectorAll("body>script[src]")`). **Preferably read the last script first**. 
3_ save the `client_id` and the script filename or url.
4_ next time, fetch the homepage and check if the script is present by using his url/filename.

Scripts contain a 4-byte hash in thier filename (like a git commit), so, any modification would lead to a new filename.

Also in step two we can check for pattern` assets\/47-[a-f0-9]+-\d\.js` or `assets\/47-[a-f0-9]{1,8}-3\.js` in the script names

**Comment by mauriciocolli** [comment]
Checking this again, the current client id changed and it seems that it's generated every time there's an update to the site now. The old one is still working, and here's the thing:

`youtube-dl` uses a old client id for 4 months now and it is still working, so that gives a pretty clear idea of what to do: hardcode the current client id and check at the first use if it's still valid, worst case scenario: a 8KB `gzip` home page request + 16KB script request, as long as that script stays at the bottom (that one seems to be always generated last according to their last updates).

To check that the client id is valid a `HEAD` request would be ideal (so we can check just by the response code), unfortunately my pull request wasn't merged yet so we don't have the improved downloader implementation (maybe I should do as a separate one). Anyway, I did a quick implementation with current one so it should work just fine.

Check it out at: c7a559a42960312b3372ebc40b58d7b6587d2d75 ([this branch](https://github.com/mauriciocolli/NewPipeExtractor/tree/fix-client-id-hardcoded)).

**Comment by TobiGr** [comment]
@mauriciocolli Sounds good. Please add a test for the hard coded url so we are notified when it is invalid.

**Comment by mauriciocolli** [comment]
@TobiGr thanks for the heads up, done.
