### ISSUE TITLE
change home page content

### ISSUE THREAD

**Issue by eomobile** [TeamNewPipe/NewPipeExtractor#206]
How can we add a playlist instead of trend videos

example https://www.youtube.com/playlist?list=PLMC9KNkIncKtPzgY-5rmhvj7fax8fdxoj

**Comment by Stypox** [comment]
This is not an issue with the extractor

**Comment by eomobile** [comment]
I mean, How do I list a playlist on youtube instead of youtube trend videos

**Comment by eomobile** [comment]
[https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTOyXCy5kzTT0ySw8W5xHojtTkoTWbYAOUU2cO-chJ2mzO8D4Y0](url)  this screen

**Comment by eomobile** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTOyXCy5kzTT0ySw8W5xHojtTkoTWbYAOUU2cO-chJ2mzO8D4Y0

**Comment by Stypox** [comment]
You currently can't, and as I said this is an issue with the app, not the extractor
