### ISSUE TITLE
YoutubePlaylistExtractor error when import Youtube Mix

### ISSUE THREAD

**Issue by Pi-Bouf** [TeamNewPipe/NewPipeExtractor#214]
I got an error when I try to import in my playlist a youtube mix like this: 
https://www.youtube.com/playlist?list=RDSlPhMPnQ58k

The error:
```
Could not get playlist name
YoutubePlaylistExtractor:55
```

I will try to fix it and make a Pull Request :)

**Comment by PeterHindes** [comment]
I believe this will be fixed by #280 . Close the issue.

**Comment by Stypox** [comment]
@PeterHindes issues should be closed when fixing prs are merged, so for now it is ok for this to stay open ;-)

**Comment by PeterHindes** [comment]
Oh, sorry my mistake.
