### ISSUE TITLE
https ssl problems with transparent proxyes

### ISSUE THREAD

**Issue by Nekham** [TeamNewPipe/NewPipeExtractor#218]
[traceback.txt](https://github.com/TeamNewPipe/NewPipeExtractor/files/3932236/traceback.txt)
Hi, I live in an university campus. The campus wi-fi is configured and managed by a Mikrotik system. All connections are forwarded throug a "transparent" proxy, tus all https connections are forwarded to my device with the ssl certs self signed by the administrator.
Normally 95 percent of applications and sites are working fine also with  this "ssl cert substitution", Newpipe is not in those. :(
When i open a video the newPipe app throws errors like the one in the attached file.

I suppose the problem is that the "xxxx.it" domain is not youtube.com and the app doesn't recognize the ssl certificate as valid.

I think that  by connecting to a vpn I can bypass the proxy and the re-signing of https connections, but maybe there are other solutions, other apps are working fine on that network.

Yes, the problem is the admin of the network that have self-signed  an https proxy without a verified CA, but contacting it is impossible.
Is it fixable?

**Comment by kapodamy** [comment]
try download the certificate and import in your certicate store (android settings >  Security & location> Advanced > Encryption & credentials)

**Comment by Nekham** [comment]
Tryed already, without success. I have same identical error.

**Comment by theScrabi** [comment]
I think newpipe does certpinning. It does not like it when its seeing different certificates. Try using VPN.

**Comment by TiA4f8R** [comment]
This is not a NewPipe Extractor issue, but a NewPipe issue. Please open an issue on the NewPipe repository if it is still reproducible. Thank you!
