### ISSUE TITLE
[just for info] Created another online youtube player with local playlists using NewPipeExtractor library

### ISSUE THREAD

**Issue by sadr0b0t** [TeamNewPipe/NewPipeExtractor#220]
Hello, just for info. I have created another online youtube player with local playlists and whitelisted recommendations, it strongly relies on NewPipeExtractor library.

Seems like it is good enough for the first beta release, please, take a look:
https://github.com/sadr0b0t/yashlang/blob/master/README.en.md

**Comment by PeterHindes** [comment]
Thank you for sharing, however it is important that we keep the issues on-topic and related to problems with the app. I would appreciate it if you could close your issue. It might make sense for the team to make a list of related projects since many people like to share their projects here.
