### ISSUE TITLE
Download from Background player screen

### ISSUE THREAD

**Issue by 1emirozdemir** [TeamNewPipe/NewPipeExtractor#221]
![Screenshot_20191208-152302](https://user-images.githubusercontent.com/35995145/70389325-fdc93200-19ce-11ea-9505-1958e2c5b0df.jpg)

ServicePlayerActivity.java 

`    @Override
    public void onClick(View view) {
        if (player == null) return;

        if (view.getId() == repeatButton.getId()) {
            player.onRepeatClicked();

        } else if (view.getId() == backwardButton.getId()) {
            player.onPlayPrevious();

        } else if (view.getId() == playPauseButton.getId()) {
            player.onPlayPause();

        } else if (view.getId() == forwardButton.getId()) {
            player.onPlayNext();

        } else if (view.getId() == shuffleButton.getId()) {
            player.onShuffleClicked();

        } else if (view.getId() == playbackSpeedButton.getId()) {
            openDownloadDialog() //////

        } else if (view.getId() == metadata.getId()) {
            scrollToSelected();

        } else if (view.getId() == progressLiveSync.getId()) {
            player.seekToDefault();

        }
    }`

how can I start downloading please help me

**Comment by TiA4f8R** [comment]
This is not at all an extractor issue. Closing as invalid.

Also, NewPipe has changed a lot since the time you opened this issue. Thank you!
