### ISSUE TITLE
DASH Streaming and Downloading Support

### ISSUE THREAD

**Issue by moriel5** [TeamNewPipe/NewPipeExtractor#223]
Hello, I was wondering whether the DASH protocol is fully supported by the extractor library, since NewPipe does not support streaming nor downloading videos via the DASH protocol.

**Comment by Stypox** [comment]
As far as I know it is currently not supported

**Comment by moriel5** [comment]
Thanks, I guess I'll have to wait until either someone adds support, or I learn enough to be able to contribute code.

**Comment by TiA4f8R** [comment]
This issue will be fixed when #810 is merged.

**Comment by moriel5** [comment]
Thanks, that's great to hear!
