### ISSUE TITLE
Decide classes naming between channel/user

### ISSUE THREAD

**Issue by mauriciocolli** [TeamNewPipe/NewPipeExtractor#23]
[This pull request](https://github.com/TeamNewPipe/NewPipeExtractor/pull/20) modified the "Channel" naming to "User".
I've been thinking a bit more about this change, and I wanted to know the opinion of you all about it. 

**EDIT**: I meant which naming, specifically for the classes of the extractor, do you prefer.

Just to know, this would impact just the way someone uses the extractor, for example:

```java
UserInfo.getInfo("url"); 
// or
ChannelInfo.getInfo("url");
```

Thinking again, I don't even know why I created an issue for such small detail, but since it's already created I'll leave open anyway to know your opinion about it.

**Comment by karyogamy** [comment]
I think this renaming should affects both the extractor and app code base, just to keep things consistent. The UI can remain the as is though (i.e. channel), since this is more of a internal refactor and it is easier for the user to understand.

**Comment by wb9688** [comment]
>show Video is the UI

Wouldn't that sound weird with SoundCloud? "I'm going to listen to a video
on SoundCloud."

**Comment by mauriciocolli** [comment]
@wb9688 yes it does, and as you read this by email (I presume, as you sent your reply by it), I already edited and add more things to it after I opened the issue.

@karyogamy yes, if "user" is decided, both of the repositories will be changed.

**Comment by TheAssassin** [comment]
As mentioned before, one could just add a name getter to every class which returns the appropriate name. Then, the implementations are in charge of the naming scheme, and an abstracted naming scheme can be used internally that is independent from anything inside NewPipe. This should further work quite well in combination with the translations.

**Comment by mauriciocolli** [comment]
I mixed both things, sorry, I meant which naming, _specifically_ for the classes of the extractor, do you prefer.

Just to know, this would impact just the way someone uses the extractor, for example:
```java
UserInfo.getInfo("url"); 
// or
ChannelInfo.getInfo("url");
```

Thinking again, I don't even know why I created an issue for such small detail, but since it's already created I'll leave open anyway to know your opinion about it.

**Comment by TheAssassin** [comment]
Looks like this discussion should've taken place in the PR anyway.

I'd say, use the more common name. What is more important to you? The API name or the one used on the site? While the latter is more visible, the API name feels more familiar in the code. The PR author shares the former thought I guess.

**Comment by mauriciocolli** [comment]
I've decided to rollback this change and use 'channel'. 

The main reason is that 'channel' is more commonly used, so it'll be more intuitive to people who just started using the extractor (another is that YouTube is more known, and that contributes to the previous reason too).
