### ISSUE TITLE
NextItemsResult does not store errors during extractions

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipeExtractor#24]
https://github.com/TeamNewPipe/NewPipeExtractor/blob/82824cdd72bfaca468935cabca0586da4794c716/src/main/java/org/schabi/newpipe/extractor/ListExtractor.java#L61

This class does not store informations about occurring errors during the extraction of a following page. We should change that.

**Comment by mauriciocolli** [comment]
Travis seems to have some network problems while connecting to SoundCloud, tests are passing locally.

https://travis-ci.org/TeamNewPipe/NewPipeExtractor#L467

>...
 Caused by: java.net.SocketTimeoutException at SoundcloudChannelExtractorTest.java:25
...

**Comment by theScrabi** [comment]
No.
This has nothing to do with the Travis failing. This class simply has not the ability do deliver errors that occurred during the extraction phase of a NextItemResult

Look at this here:
https://github.com/TeamNewPipe/NewPipeExtractor/blob/9184fc509c61b3e9a1fba657d1761f5778f5e426/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeChannelExtractor.java#L147

In this class the collector gets put into the NextItemResult. Now here:
https://github.com/TeamNewPipe/NewPipeExtractor/blob/9184fc509c61b3e9a1fba657d1761f5778f5e426/src/main/java/org/schabi/newpipe/extractor/ListExtractor.java#L78
the ItemList is taken form the collector, but not the error list, therefore the errors get lost.
I don't know if errors of a next page got handled before the refactoring, but we should enable this again.

By the way you are doing a great work. Keep it up :+1:

**Comment by mauriciocolli** [comment]
I was talking about the commit that failed in Travis.

But I don't understand, I **_am_** passing the errors just like the `Info` does:
> this(collector.getItemList(), nextItemsUrl, **_collector.getErrors()_**);

Thanks!

**Comment by theScrabi** [comment]
Uch right,
you are right, I'm sorry, I didn't see the `collector.getErrors()`.
