### ISSUE TITLE
Can you help me with any complete example of live audio streaming in kotlin or java? 

### ISSUE THREAD

**Issue by faizanurrehaman** [TeamNewPipe/NewPipeExtractor#240]
I am unable to find the code how to stream the mp3 file in documents and download a mp3.
can anybody help me ?

**Comment by PeterHindes** [comment]
How is this related to NewPipe?

**Comment by Stypox** [comment]
@faizanurrehaman You could take a look at the ExoPlayer: https://github.com/google/ExoPlayer
However, this has nothing to do with NewPipe, as PeterHindes pointed out, so I'm closing it ;-)
