### ISSUE TITLE
Can't play any YouTube video / Could not parse decrypt function

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipeExtractor#241]
See https://github.com/TeamNewPipe/NewPipe/issues/2981
and the crash report:
https://github.com/TeamNewPipe/NewPipe/issues/2981#issuecomment-577840425

**Comment by CWftw** [comment]
Probably related to Youtube-DL issue: https://github.com/ytdl-org/youtube-dl/issues/23819

**Comment by opusforlife2** [comment]
@TobiGr @Stypox yt-dl seems to have fixed this? https://github.com/ytdl-org/youtube-dl/commit/c3cfea906869e8358652e382679a5996c2aec73e

**Comment by TobiGr** [comment]
``` 
'\b(?P<sig>[a-zA-Z0-9$]{2})\s*=\s*function\(\s*a\s*\)\s*{\s*a\s*=\s*a\.split\(\s*""\s*\)'
```
Adopting the Python Regex into the Java extractor seems to be more difficult than i I thought.
It should be added [here](https://github.com/TeamNewPipe/NewPipeExtractor/blob/e0758db741acf75afb87d0d2bb111d1079e68d41/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L701) and [here](https://github.com/TeamNewPipe/NewPipeExtractor/blob/e0758db741acf75afb87d0d2bb111d1079e68d41/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L893). However, the regex does not work for me. Can someone help e with that?

**Comment by theScrabi** [comment]
Ah uff. Can you post the old function here?

**Comment by TobiGr** [comment]
Old plain Regex
```
([\w$]+)\s*=\s*function\((\w+)\)\{\s*\2=\s*\2\.split\(""\)\s*;
```
Old Regex in Java
```
([\\w$]+)\\s*=\\s*function\\((\\w+)\\)\\{\\s*\\2=\\s*\\2\\.split\\(\"\"\\)\\s*;
```

**Comment by theScrabi** [comment]
Bad idea but maybe this helps: https://stackoverflow.com/questions/2945783/easy-way-to-convert-regex-to-a-java-compatible-regex

**Comment by theScrabi** [comment]
I am no expert as i have not worked on this for a while, but issnt named groups `(?<sig>` something that is not possible in java? For this i always used the match group one function from the Parser helper class.

**Comment by TobiGr** [comment]
Yes. `?P<sig>` need to be removed as well as `\b`

**Comment by theScrabi** [comment]
In python doc `\b` is defined:
https://docs.python.org/3/library/re.html

As

Matches the empty string, but only at the beginning or end of a word. A word is defined as a sequence of word characters. Note that formally, \b is defined as the boundary between a \w and a \W character (or vice versa), or between \w and the beginning/end of the string. This means that r'\bfoo\b' matches 'foo', 'foo.', '(foo)', 'bar foo baz' but not 'foobar' or 'foo3'.

**Comment by TobiGr** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/commit/ad63304afda30a158a2f01aedaaafb7ad9322727

**Comment by theScrabi** [comment]
So maybe you could replace this with something like `[ .\(\)].`. But im not super shure. You could however go into debug mode and get the player url which you can download. Then you could try and find out what came before the `<sig>` group. Then you may be able to match it more closely.

**Comment by theScrabi** [comment]
> ad63304

Nnice 😍

**Comment by TobiGr** [comment]
@theScrabi Can you take care of the release? I'll need to be at university tomorrow morning at 8am and at least some hours of sleep would be nice.

**Comment by infinitytec** [comment]
Hey guys! Thanks for a fast fix once again!

**Comment by B0pol** [comment]
This issue is closed but dev branches of NewPipe and NewPipeExtractor still have this issue.
