### ISSUE TITLE
Video Not Available - reCaptcha Challenge Requested

### ISSUE THREAD

**Issue by SArsalanK** [TeamNewPipe/NewPipeExtractor#246]
Every time I try to load a video the vide isn't available and the screen directs to the reCaptcha screen. Please have a look at the screenshots below. Thanks 

https://www.dropbox.com/s/dvijv8mbnxqluva/1.jpg?dl=0
https://www.dropbox.com/s/jnyrlc674qerhtd/2.jpeg?dl=0

**Comment by Stypox** [comment]
Duplicate of TeamNewPipe/NewPipe#2924
