### ISSUE TITLE
Plsese Fix Pleased I'm Used NewPipeExtractor:v0.17.4 

### ISSUE THREAD

**Issue by cion49235** [TeamNewPipe/NewPipeExtractor#249]
I'm Used version NewPipeExtractor:v0.17.4 version Source

But closed issues NewPipeExtractor:v0.18.2 finished  

Please correct the decoding problem in this version as well. I beg you. NewPipeExtractor:v0.17.4

Please Please .... Im Used ==>implementation 'com.github.teamnewpipe:NewPipeExtractor:v0.17.4'
================================================================

{
   "user_action": "requested stream",
   "request": "https:\/\/www.youtube.com\/watch?v=4C8CptPlllQ",
   "content_language": "GB",
   "service": "YouTube",
   "package": "org.schabi.newpipe.debug",
   "version": "0.18.0",
   "os": "Linux Android 10 - 29",
   "time": "2020-01-24 14:08",
   "exceptions": [
      "org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function \n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:849)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:716)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:60)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:919)\nCaused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern \";([A-Za-z0-9_\\$]{2})\\...\\( inside of var lea=function(a){a=a.split(\"\");var b=[function(c,d){d=(d%c.length+c.length)%c.length;c.splice(-d).reverse().forEach(function(e){return c.unshift(e)};\"\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:73)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:836)\n\t... 30 more\n"
   ],
   "user_comment": ""
}

**Comment by Stypox** [comment]
Use 0.18.2, why would you use an outdated version?

**Comment by Stypox** [comment]
Just use `implementation 'com.github.teamnewpipe:NewPipeExtractor:v0.18.2'`

**Comment by TobiGr** [comment]
If you want to stay on the 0.17.4 branch, feel free to cherry pick the commits from #243 in your own fork and then use `implementation com.github.cion49235:NewPipeExtractor:SHA_FROM_HEAD`

**Comment by cion49235** [comment]
> Use 0.18.2, why would you use an outdated version?



> Just use `implementation 'com.github.TeamNewPipe:NewPipeExtractor:v0.18.2'`

I know you can use v0.18.2 However, if I use this version, it is hard to lose because there are so many things to modify.  Please correct the decoding problem for v0.17.4 version as well.

**Comment by jhorner6511** [comment]
Hello Everyone. I am neither a spokesperson nor a representative of SkyTube or NewPipe, however, I am here to inform you all that the reason why both apps are not working has nothing to do with the apps themselves. Unfortunately, YouTube/Google has updated their policies recently, along with their algorithms, and is now preventing such apps from scraping their videos. YouTube now requires that any app that scrapes its website for content, like SkyTube or NewPipe, they must now enter a reCAPTCHA to verify it's a human being that is scraping the content.

All respective developers of both apps are aware of the issue and are in the process of figuring out a workaround to Google's new algorithm. Please pay attention for any new updates and/or comments from the developers in the near future. On their behalf, we apologize for any inconvenience this has caused you.

**Comment by TobiGr** [comment]
Um @jhorner6511. The reCAPTCHA has nothing to do with NewPipe 0.18.1 and earlier stopped working on Thursday. There was a change by YouTube on the way, info is stored.

@cion49235 Did my instruction help you to create your own 0.17.5 version?
