### ISSUE TITLE
How to Local project import

### ISSUE THREAD

**Issue by tolgatasci** [TeamNewPipe/NewPipeExtractor#252]
settings.grandle
```
include ':app'
include ':NewPipeExtractor'
```
 //implementation 'com.github.TeamNewPipe:NewPipeExtractor:ff61e284'

implementation project(':NewPipeExtractor')

error 

Project with path ':extractor' could not be found in project ':NewPipeExtractor'.

**Comment by PeterHindes** [comment]
Did you find a solution? I'm trying to do the same.

**Comment by tolgatasci** [comment]
no bro :( google play no accept this code

**Comment by PeterHindes** [comment]
What does Google play have to do with this?

**Comment by tolgatasci** [comment]
https://github.com/TeamNewPipe/NewPipe
edit and send no accept

**Comment by PeterHindes** [comment]
That's still not making sense to me.

**Comment by B0pol** [comment]
Read the docs:

Part "Using local folder"
https://teamnewpipe.github.io/documentation/04_Run_changes_in_App/
