### ISSUE TITLE
Heads up, YouTube discontinuing older version on desktop soon

### ISSUE THREAD

**Issue by yausername** [TeamNewPipe/NewPipeExtractor#258]
This might affect us.

> Enter 2020 and the older versions are missing many of the new features and design improvements we’ve introduced over the past 3 years, including top requests based on your feedback (see most recent update here). That's why the older version will be going away in March and you'll only be able to access newer desktop versions to enjoy the best of YouTube.

https://support.google.com/youtube/thread/27596769

**Comment by TobiGr** [comment]
Uuh f***. We need to switch to the new version asap.

**Comment by TobiGr** [comment]
Which user agent is the best to use?

**Comment by TobiGr** [comment]
Using `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/73.0` changes everything...
Most info about the current video or channel is stored in `window["ytInitialData"]`.
I have created a new branch: [yt_new](https://github.com/TeamNewPipe/NewPipeExtractor/tree/yt_new).

**Comment by B0pol** [comment]
How do you read the json file?
Firefox says json has errors, and shows nothing
For the YoutubeStreamExtractor, I used [this website](https://jsonformatter.curiousconcept.com/), it said it has error but was still formatting
But for the channelExtractor, it says it has too many errors and it can't format it.

So do you have any tips or you are reading the unformatted file?

**Comment by wb9688** [comment]
@B0pol: I could read the JSON file perfectly fine. Anyway, I'm already working on it.

**Comment by TobiGr** [comment]
@B0pol I've zipped most important sites: [documents.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/4219470/documents.zip)

**Comment by B0pol** [comment]
perfect, thank you

**Comment by B0pol** [comment]
Ok I found why it bugged:
the files I got written didn't include the quotes "
What i did was:

``createFile("yt_new/initialData.json", extractor.getPlayerResponse().toString());``
with createFile:
```java
public static void createFile(String path, String content) throws IOException {
    BufferedWriter writer = new BufferedWriter(new FileWriter(path));
    writer.write(content);
    writer.flush();
    writer.close();
}
```

I read [nanojson git](https://github.com/mmastrac/nanojson/blob/master/README.md#writer-example) and the proper way to do it isn't ``an instance of JsonObject.toString()``, but
``String json = JsonWriter.string(JsonObject or JsonArray);``

**Comment by TobiGr** [comment]
@Poolitzer Do you have time to prepare a blog post? We are preparing a new release to address this before everything stops working.

**Comment by Poolitzer** [comment]
Always

**Comment by B0pol** [comment]
It's april and old youtube is still available by adding &app=desktop in url :o

**Comment by Poolitzer** [comment]
How dare they tricking us into using their new version which offers way more features like those fancy new feed streams and stuff.
