### ISSUE TITLE
Please, add Youtube login feature :(

### ISSUE THREAD

**Issue by ibrahimlee** [TeamNewPipe/NewPipeExtractor#260]

**Comment by ibrahimlee** [comment]
I renew cookies by logging into Youtube with Webview, but kiosks only return trends

**Comment by Stypox** [comment]
From [FAQ](https://newpipe.schabi.org/FAQ/bugs/):
> NewPipe's goal is to as effectively as possible protect its user's privacy. This means, the app only sends information to external servers which is needed to view search results or watch videos.
Having said this, the developers of NewPipe hope it is understandable that they will not implement any form of authentication which might allow tracking a user.
