### ISSUE TITLE
Mixed Streams only 360p

### ISSUE THREAD

**Issue by johnsky95** [TeamNewPipe/NewPipeExtractor#282]
Hi.

I am not reporting any bug or asking for any new feature, but I am curious a lot.
Why we cannot get mixed stream more than 360|720p? 

I can see IDM (internet download manager) can download videos at 1080p|2k|4k even with audio, is there any trick there?

**Comment by wb9688** [comment]
IDM probably combines the audio and video streams with ffmpeg or whatever after downloading them both. Look at youtube-dl -F to see what streams YouTube offers. And yes, it's true that NewPipeExtractor doesn't offer all itags yet.
