### ISSUE TITLE
ParsingException: Could not get channel id

### ISSUE THREAD

**Issue by artsemionov** [TeamNewPipe/NewPipeExtractor#283]
There are some channels where I get this exception.

There are regular channels where id has changed and page is redirecting to new id:
https://www.youtube.com/channel/UCZo_3DUateypfhV_fytbwWA
https://www.youtube.com/channel/UCITk7Ky4iE5_xISw9IaHqpQ

Same behavior, but different ids redirecting to same Youtube's "Movies & Shows" channel:
https://www.youtube.com/channel/UCuJcl0Ju-gPDoksRjK1ya-w
https://www.youtube.com/channel/UChBfWrfBXL9wS6tQtgjt_OQ
https://www.youtube.com/channel/UCok7UTQQEP1Rsctxiv3gwSQ

Some channels where id hasn't changed but still getting same exception:
https://www.youtube.com/channel/UC0KU8F9jJqSLS11LRXvFWmg
https://www.youtube.com/channel/UCHcMtE3EiKmqrJZBZyUBuRQ

**Comment by wb9688** [comment]
I can't reproduce this. Where does it happen?

**Comment by bunaif** [comment]
@wb9688  

> There are regular channels where id has changed and page is redirecting to new id:
https://www.youtube.com/channel/UCZo_3DUateypfhV_fytbwWA
https://www.youtube.com/channel/UCITk7Ky4iE5_xISw9IaHqpQ

[Screen_Recording_20200309-232821.mp4.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/4308577/Screen_Recording_20200309-232821.mp4.zip)
