### ISSUE TITLE
Streams with signature don't work anymore

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipeExtractor#29]
After the refactoring videos with signatures don't play anymore We have to fix that asap. Since this is an important part of the extractor.
I took a look a the code, and it seems that the error exists somewhere [here](https://github.com/TeamNewPipe/NewPipeExtractor/blob/master/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java#L706).
This is the line where the new URL with the decrypted signature gets created.

However the extractor of the current working version of NewPipe [v0.9.10](https://github.com/TeamNewPipe/NewPipeExtractor/blob/97ad1a2052bd880f39ac62712274d78a2917ca05/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java#L681) does seem to use the same code. So it's a bit more tricky. Hover I'm not at home right now so I can't use my computer. Otherwise I would have checked the URLs the old extractor produces, and compared it to the URLs the new one produces.

**Comment by mauriciocolli** [comment]
After a quick overview, I discovered some things:

When the video is not age restricted:
- The signature is not correctly decrypted when using a tag/url from the `videoInfoPage`
- When it comes from `playerArgs` it works correctly

When it is age restricted:
- The signature comes already decrypted in the `videoInfoPage`
- Field `playerArgs` is not initialized

So a very simple fix is to swap the `if-else`, as the playerArgs will be null when the video is age restricted.

**Comment by theScrabi** [comment]
All right thanks.
