### ISSUE TITLE
api.soundcloud.com can't be used anymore

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipeExtractor#290]
On IRC we came to the conclusion that we can't use api.soundcloud.com anymore with SoundCloud's client ID, so we'll have to rewrite those parts of NewPipeExtractor to use api-v2.soundcloud.com.

**Comment by wb9688** [comment]
I don't think this is true, as it works fine for me on the `master` branch here???

**Comment by opusforlife2** [comment]
Shouldn't this have been closed by #293?

**Comment by wb9688** [comment]
@opusforlife2: Yes, though there are still problems with our current SoundCloud implementation.
