### ISSUE TITLE
getSubscriberCount returns 0 incorrectly for YouTube

### ISSUE THREAD

**Issue by gzsombor** [TeamNewPipe/NewPipeExtractor#305]
It seems that after [this](https://github.com/TeamNewPipe/NewPipeExtractor/commit/0798bdd5cd03bb44c0593a28b9c23df472e762ef#diff-1c13023aae5fe2aea7edc4e2a7658e15) getSubscriberCount returns 0 even when there is no known subscriber count, for example [here](https://www.youtube.com/channel/UCC76FBg2d-5NWFD8aK4ql5A/). I'm sure, this channel has more than 0 subscriber, just hidden, but as it has a 'Subscribe' button, which misleads the code a bit.
 
Found in https://github.com/ram-on/SkyTube/issues/728

**Comment by wb9688** [comment]
@B0pol is the one who suggested to do that iirc

**Comment by B0pol** [comment]
Let's say why:
[This channel has subscriber count disabled](https://www.youtube.com/user/EminemVEVO)
[This one has subscriber count hidden](https://invidious.snopyta.org/channel/UCC76FBg2d-5NWFD8aK4ql5A/?quality=hd720)
These channels that I took randomly [1](https://www.youtube.com/channel/UCt0C6KTStiWiaA_4Urxd8zw) [2](https://www.youtube.com/channel/UCanjUR3mC8MyDlPwRhREZfQ) [3](https://www.youtube.com/channel/UC08d7UwAOnN3t98ZJAfHwcQ) are extremely likely to have 0 subscribers count indeed.
BUT, the thing is, there is no way to difference 0 subscribers from hidden subscribers.

Then IMO, it should stay like that. With #312, you remove a clarification: the difference between (hidden|0) from disabled. 

It's up to you in your front-end to handle 0 as, if you want: hidden, or really 0. But not NPE.
The only thing that should be changed is javadoc: add a precision for YouTube, 0 can mean hidden sometimes.

**Comment by gzsombor** [comment]
For me, for the API user, returning 0 as a subscriber count means, that it has 0 subscriber. If it returns -1 or null or any other value, which is not a whole number, this is means, that the value is unknown. 
But returning -1 or 0 based on if it has a subscriber button marker in the json - it doesn't make any sense to me, and this doesn't seem to relate if the channel has 0 subscriber or infinite number of them.
It would be even better, if the API could return Optional.empty() or null - I don't really want to use -1 to mark a.
