### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by LucasLassiter** [TeamNewPipe/NewPipeExtractor#316]
I'm pretty new to Android Development and just a high school student and have tried for a couple hours to wrap my head around all of this, I guess I just don't know enough yet, what do I first have to learn to be able to understand what to do? I basically just want to download videos from Youtube using this, and it seems like I need an extractor, downloaders, parser, and all these things and are abstract classes, so I guess I just don't know what I need to put inside them to do stuff. I'm still pretty new to coding so I thought it would just be downloader.getVideo("inserturl"), but it's obviously way more complicated than that lol.

**Comment by wb9688** [comment]
Take a look at [the relevant tests for an example on how to use NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/stream/YoutubeStreamExtractorDefaultTest.java) and [an example implementation of `Downloader`](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/test/java/org/schabi/newpipe/DownloaderTestImpl.java).

**Comment by LucasLassiter** [comment]
Thanks so much, I'll try these and see if I'm able to get a better grasp on this!
