### ISSUE TITLE
URL unsupported with youtu.be shortened links + timestamps

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipeExtractor#318]
Try with https://youtu.be/Nj2U6rhnucI?t=8s for example. "URL unsupported".

**Comment by Stypox** [comment]
For me it works in NewPipe 0.19.2, also there already is a (succeeding) test for this [here](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamLinkHandlerFactoryTest.java#L73). Could you explain how to reproduce?

**Comment by B0pol** [comment]
I can't reproduce now. So weird…

**Comment by B0pol** [comment]
Update: it was another app intercepting the url and not handling the timestamps and I could not reproduce because I uninstalled it for a time.

(The app is [UntrackMe](https://f-droid.org/app/app.fedilab.nitterizeme) redirecting youtube, twitter and instagram to invidious, nitter and bibliogram.)
