### ISSUE TITLE
[Service request] Bitchute

### ISSUE THREAD

**Issue by yashx** [TeamNewPipe/NewPipeExtractor#320]
Can [Bitchute](https://www.bitchute.com/) be added as a service in Newpipe?
I will try to implement it. I just want to be sure if it will be allowed on the official app.

**Comment by wb9688** [comment]
See the bottom of https://teamnewpipe.github.io/documentation/00_Prepare_everything/ for the inclusion criteria

**Comment by yashx** [comment]
@wb9688 From what I read on their content policy it should be alright.

It's just that the platform had some negative press initially so I just wanted to be sure that the maintainers here were okay with it being included.

**Comment by yashx** [comment]
@wb9688 @TobiGr Bitchute's search doesn't work. Can I scrape results from search engines (like Google, duckduckgo, etc)?

**Comment by wb9688** [comment]
>Bitchute's search doesn't work.

@yashx: What do you mean? I just get results when searching something at https://www.bitchute.com/

>Can I scrape results from search engines (like Google, duckduckgo, etc)?

No, try to figure out why you can't just search on BitChute.

**Comment by yashx** [comment]
@wb9688 I mean it works but it is bad. From what I know they have a small team and they still haven't fixed it. 
I can show results from their website but from what I have seen Google, Bing, etc do a better job.
I know it is a roundabout way to implement search but it would give a better user experience.

**Comment by TobiGr** [comment]
See https://github.com/TeamNewPipe/NewPipeExtractor/pull/325#issuecomment-626801193
