### ISSUE TITLE
Signature cipher extraction failing

### ISSUE THREAD

**Issue by CWftw** [TeamNewPipe/NewPipeExtractor#327]
We are seeing many scraping failures presumably caused by this issue. Solution in YouTube-DL

https://github.com/ytdl-org/youtube-dl/commit/fa3db383330501f00fb0353a3989aef272b571f2

**Comment by wb9688** [comment]
Who is "we"? Also, I've seen some videos not play indeed, and I'll make a PR doing the same as the commit you linked soon.

**Comment by TobiGr** [comment]
Does this require a hotfix release?

**Comment by wb9688** [comment]
@TobiGr: I don't think so. Only some users (not me at least) see it on some videos I think.

**Comment by TobiGr** [comment]
@wb9688 I cannot reproduce it, too. I'll merge this into `dev`, but if we get more reports like this, I'll release a hotfix version.
