### ISSUE TITLE
Rework README.md

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipeExtractor#33]
Now since we offer NewPIpeExtractor as a maven repo we might consider to rework the README.md. Also we might add a guide for how to develop the extractor/own services.

**Comment by mauriciocolli** [comment]
Is "maven repo" correct/precise enough? 

We are currently using [jitpack.io](https://jitpack.io/) and people may confound this with the maven repository itself, and because of that, not be able to compile/fetch the extractor.

**Comment by TheAssassin** [comment]
More off-topic: Can someone update the F-Droid description? It is not really appropriate any more, and for PR reasons, we should provide a good text there.

**Comment by theScrabi** [comment]
@mauriciocolli you are right. We should fix that.
@TheAssasine, I can update the description if we decide on an appropriate text.
