### ISSUE TITLE
new clip format 

### ISSUE THREAD

**Issue by sanyouyugan** [TeamNewPipe/NewPipeExtractor#335]
"adaptiveFormats":[
            {
                "itag":137,
                "mimeType":"video/mp4; codecs="avc1.640028"",
                "bitrate":2365369,
                "width":1920,
                "height":1080,
                "initRange":{
                    "start":"0",
                    "end":"741"
                },
                "indexRange":{
                    "start":"742",
                    "end":"941"
                },
                "lastModified":"1588337394223444",
                "contentLength":"15766074",
                "quality":"hd1080",
                "fps":25,
                "qualityLabel":"1080p",
                "projectionType":"RECTANGULAR",
                "averageBitrate":1784501,
                "approxDurationMs":"70680",
                "signatureCipher":"s=9cOq0QJ8wRQIhANg5UzR0lC7l6EcD5KcVKCbzzsOnJBVA6kICcI1bkEueAiBOc28fBUUfYb_KRMfJSd4Ee-FOs__ZMEYioWL6zUW9wg%3D%3D%3D%3D&sp=sig&url=https://r4---sn-n4v7sn76.googlevideo.com/videoplayback%3Fexpire%3D1590653356%26ei%3DTB3PXomMOImukwai9aVw%26ip%3D12.0.207.22%26id%3Do-AEk8KUeo4-GsRVuHtlaifyWeHj0imF0m_w2ENglxCPZ8%26itag%3D137%26aitags%3D133%252C134%252C135%252C136%252C137%252C160%252C242%252C243%252C244%252C247%252C248%252C278%252C597%252C598%26source%3Dyoutube%26requiressl%3Dyes%26mh%3Dih%26mm%3D31%252C26%26mn%3Dsn-n4v7sn76%252Csn-a5mlrn7y%26ms%3Dau%252Conr%26mv%3Dm%26mvi%3D3%26pl%3D21%26initcwndbps%3D1045000%26vprv%3D1%26mime%3Dvideo%252Fmp4%26gir%3Dyes%26clen%3D15766074%26dur%3D70.680%26lmt%3D1588337394223444%26mt%3D1590631660%26fvip%3D4%26keepalive%3Dyes%26c%3DMWEB%26txp%3D5535432%26sparams%3Dexpire%252Cei%252Cip%252Cid%252Caitags%252Csource%252Crequiressl%252Cvprv%252Cmime%252Cgir%252Cclen%252Cdur%252Clmt%26lsparams%3Dmh%252Cmm%252Cmn%252Cms%252Cmv%252Cmvi%252Cpl%252Cinitcwndbps%26lsig%3DAG3C_xAwRQIgG3LuX_G03ZHDSGwuxvgPC0VPv2BlDNZ2j6SdlbD-FgECIQD8OVlMFiAnYcoD4mZmWx4WX5BKgS6Zs6qHGNGcMk4_iw%253D%253D"
            },
            {
                "itag":248,
                "mimeType":"video/webm; codecs="vp9"",
                "bitrate":2113017,
                "width":1920,
                "height":1080,
                "initRange":{
                    "start":"0",
                    "end":"219"
                },
                "indexRange":{
                    "start":"220",
                    "end":"448"
                },
                "lastModified":"1588337189918258",
                "contentLength":"14380326",
                "quality":"hd1080",
                "fps":25,
                "qualityLabel":"1080p",
                "projectionType":"RECTANGULAR",
                "averageBitrate":1627654,
                "colorInfo":{
                    "primaries":"COLOR_PRIMARIES_BT709",
                    "transferCharacteristics":"COLOR_TRANSFER_CHARACTERISTICS_BT709",
                    "matrixCoefficients":"COLOR_MATRIX_COEFFICIENTS_BT709"
                },
                "approxDurationMs":"70680",
                "signatureCipher":"s=-QOq0QJ8wRQIgOd-Bzmd8EsI-sxQIU67Pa9KNGIqCaqCA0Sxamv_yaXUCIQD905_K6-JVuRoeI1Ekodx70ECsq9Jyp7rkoRpXS8rVyg%3D%3D%3D%3D&sp=sig&url=https://r4---sn-n4v7sn76.googlevideo.com/videoplayback%3Fexpire%3D1590653356%26ei%3DTB3PXomMOImukwai9aVw%26ip%3D12.0.207.22%26id%3Do-AEk8KUeo4-GsRVuHtlaifyWeHj0imF0m_w2ENglxCPZ8%26itag%3D248%26aitags%3D133%252C134%252C135%252C136%252C137%252C160%252C242%252C243%252C244%252C247%252C248%252C278%252C597%252C598%26source%3Dyoutube%26requiressl%3Dyes%26mh%3Dih%26mm%3D31%252C26%26mn%3Dsn-n4v7sn76%252Csn-a5mlrn7y%26ms%3Dau%252Conr%26mv%3Dm%26mvi%3D3%26pl%3D21%26initcwndbps%3D1045000%26vprv%3D1%26mime%3Dvideo%252Fwebm%26gir%3Dyes%26clen%3D14380326%26dur%3D70.680%26lmt%3D1588337189918258%26mt%3D1590631660%26fvip%3D4%26keepalive%3Dyes%26c%3DMWEB%26txp%3D5535432%26sparams%3Dexpire%252Cei%252Cip%252Cid%252Caitags%252Csource%252Crequiressl%252Cvprv%252Cmime%252Cgir%252Cclen%252Cdur%252Clmt%26lsparams%3Dmh%252Cmm%252Cmn%252Cms%252Cmv%252Cmvi%252Cpl%252Cinitcwndbps%26lsig%3DAG3C_xAwRgIhALss2ClOEofTDevl6c5qYike4fctlA8sfUvIh0jmnMMfAiEAvC2VBCRUiTpUddbo6bzUdvyat4tAsirX3r3BbrIpFTQ%253D"
            },

https://www.youtube.com/watch?v=Oxbsh7JCfiM

the cliper filed has been changed

**Comment by TiA4f8R** [comment]
This issue is outdated and should have been fixed. If not, please let us know.

Thank you!
