### ISSUE TITLE
how Can I get DashMpdUrl?

### ISSUE THREAD

**Issue by poptong** [TeamNewPipe/NewPipeExtractor#356]
i want youtube dashmpdurl

how Can I get DashMpdUrl?

**Comment by jatin-lakhani** [comment]
+1

**Comment by wb9688** [comment]
Did you even take a look at the code? https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/stream/StreamExtractor.java#L223
