### ISSUE TITLE
YoutubeSubscriptionExtractor: Support new binary format

### ISSUE THREAD

**Issue by caugner** [TeamNewPipe/NewPipeExtractor#384]
The YouTube subscription export now comes in the form of a `subscription_manager.bin` file and is not currently supported by NewPipe, see: https://github.com/TeamNewPipe/NewPipe/issues/4075

**Comment by wb9688** [comment]
Could you upload an example .bin file?

**Comment by Stypox** [comment]
@wb9688 https://github.com/TeamNewPipe/NewPipe/issues/1839#issuecomment-433720822

**Comment by wb9688** [comment]
@Stypox: That's just the browser failing to set the required cookies for downloading the file causing YouTube to return the login page. I.e. there is no new file format and there is nothing wrong in NewPipe.

**Comment by opusforlife2** [comment]
This should be added to the FAQ.

**Comment by Stypox** [comment]
No, it should be added to the string explaining youtube subscription import

**Comment by seangranger** [comment]
When I download I receive a json file
