### ISSUE TITLE
Remove duplicate variable declarations

### ISSUE THREAD

**Issue by facadeproof** [TeamNewPipe/NewPipeExtractor#385]
I get the following error 

```
class org.schabi.newpipe.extractor.stream.SubtitlesStream declares multiple JSON fields named url
```
Due to this duplicate declaration of the variable `url` in [`org.schabi.newpipe.extractor.stream.Stream`](https://github.com/TeamNewPipe/NewPipeExtractor/blob/5ac80624a40f4c600ae493e66881b5bf008f0ddb/extractor/src/main/java/org/schabi/newpipe/extractor/stream/Stream.java#L15) and [`org.schabi.newpipe.extractor.stream.SubtitlesStream`](https://github.com/TeamNewPipe/NewPipeExtractor/blob/5ac80624a40f4c600ae493e66881b5bf008f0ddb/extractor/src/main/java/org/schabi/newpipe/extractor/stream/SubtitlesStream.java#L11)

**Comment by wb9688** [comment]
How are you even getting that error?

Also see #350
