### ISSUE TITLE
How can I get a list of videos from a channel or playlist?

### ISSUE THREAD

**Issue by poptong** [TeamNewPipe/NewPipeExtractor#395]
ex)
CHANNEL =>  https://www.youtube.com/user/ArianaGrandeVevo/videos
PLAYLIST => https://www.youtube.com/playlist?list=PLT5kE8dBKiP64BY4BaGA0ImNO1JfUu4e4

ChannelInfo info = ChannelInfo.getInfo(url);
When I use this, I only get channel information

What I want is a video list of channels or playlists

**Comment by wb9688** [comment]
`ListInfo` has a `getRelatedItems()` method

**Comment by poptong** [comment]
how Only the live broadcast video list in the channel??
