### ISSUE TITLE
Get YT live stream list from channel

### ISSUE THREAD

**Issue by poptong** [TeamNewPipe/NewPipeExtractor#396]
ChannelInfo info = ChannelInfo.getInfo(url);
info.getRelatedItems();
I got a list of videos from the channel, but I didn't get a list of live videos

How can I get a all video list  for a channel?

**Comment by Stypox** [comment]
Afaik live videos would be part of that list, though I could be wrong

**Comment by poptong** [comment]
how Only the live broadcast video list in the channel or playlist??

**Comment by Stypox** [comment]
You could filter the related streams by checking if they are livestreams

**Comment by poptong** [comment]
> You could filter the related streams by checking if they are livestreams



> You could filter the related streams by checking if they are livestreams

Thanks for any help.
Do you have any examples?
I have a lot of difficulties because I am not familiar with Java.

**Comment by Stypox** [comment]
Something like this should do:
```java
List<InfoItem> relatedItems = channel.getRelatedStreams();
List<StreamInfoItem> livestreams = new ArrayList<>();
for (InfoItem item : relatedItems) {
    if (item instanceof StreamInfoItem) {
        StreamInfoItem streamItem = (StreamInfoItem)item;
        if(streamItem.getStreamType() == StreamType.LIVE_STREAM || streamItem.getStreamType == StreamType.AUDIO_LIVE_STREAM) {
            livestreams.add(streamItem);
        }
    }
}
```
