### ISSUE TITLE
Use the Java 8 Date/Time API instead of the legacy Date and Calendar classes.

### ISSUE THREAD

**Issue by Isira-Seneviratne** [TeamNewPipe/NewPipeExtractor#398]
Android Gradle plugin 4.0.0 and higher support [Java 8 API desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring), which allows some Java 8 APIs (including the Date/Time API, which would normally only be available on API level 26 and higher) to be used regardless of API level.

With that in mind, I think it'd be a good idea to switch to the new Date/Time API.

**Comment by wb9688** [comment]
That's actually a feature of D8/R8 and supports up to Java 11 iirc, but only up to Java 8 for Android code (which the extractor isn't) due to limitations AGP currently has.

**Comment by Isira-Seneviratne** [comment]
Some Java 9 methods are also supported, such as the collection factory methods introduced in API level 30.

**Comment by wb9688** [comment]
Stuff like `var` is also supported, but again not for Android code (i.e. could be used in NewPipeExtractor, but not in NewPipe).

Also I'm not sure if F-Droid has deployed the stuff for newer Gradle versions yet. I'll ask on IRC.

**Comment by Isira-Seneviratne** [comment]
> Stuff like `var` should also be supported, but again not for Android code (i.e. could be used in NewPipeExtractor, but not in NewPipe).

`var` is supported. More info can be found here: https://jakewharton.com/androids-java-9-10-11-and-12-support/

**Comment by wb9688** [comment]
@Isira-Seneviratne: Yes, by D8/R8, but you'll need to be able to compile your code on your target Java version (i.e. Java 12), which isn't possible for Android code (i.e. NewPipe, but not NewPipeExtractor), as Android Gradle Plugin only works on Java versions up to Java 8, due to depending on bootclasspath.

**Comment by Isira-Seneviratne** [comment]
> @Isira-Seneviratne: Yes, by D8/R8, but you'll need to be able to compile your code on your target Java version (i.e. Java 12), which isn't possible for Android code (i.e. NewPipe, but not NewPipeExtractor), as Android Gradle Plugin only works on Java versions up to Java 8, due to depending on bootclasspath.

I didn't know that, thanks for the info.
