### ISSUE TITLE
Implement a desktop app to test and debug extractors right on desktop

### ISSUE THREAD

**Issue by KOLANICH** [TeamNewPipe/NewPipeExtractor#401]

**Comment by Stypox** [comment]
You can already test and debug extractors using the already existing Junit tests

**Comment by opusforlife2** [comment]
So... close?

**Comment by KOLANICH** [comment]
Tests are fine for automatic testing as CI pipelines. But do they test the effect the changes in an extractor cause in the app? I mean, to make sure everything is OK and works as intended (i.e. the stuff in the app 1-to-1 maps to the stuff on the website) one has to build and use the actual android app.

**Comment by Stypox** [comment]
That's true, but having a desktop app wouldn't solve the problem, since if something works on desktop doesn't mean it works on Android
