### ISSUE TITLE
Playing a stream does not switch the player to landscape mode anymore

### ISSUE THREAD

**Issue by johanw666** [TeamNewPipe/NewPipeExtractor#407]
Auto rotate screen is off on my phone. When I taped the play icon in 0.19.8, the palyer went automatically to landscape mode. In 0.20.0, I have to stop playing and then tap the maximize icon to get it play in landscapoe mode. Is there a way in 0.20 to automatically lett NewPipe switch to landscape, as before?

**Comment by opusforlife2** [comment]
Why did you open the issue in the extractor? O.o

Follow https://github.com/TeamNewPipe/NewPipe/issues/4152.

@TobiGr or someone, close. I don't have write permissions in this repo.

**Comment by johanw666** [comment]
Sorry I didn't know of that topic.
