### ISSUE TITLE
Compatibility with Video Hostings

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipeExtractor#421]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I would like Newpipe to be compatible with Video Hostings such as streamplay, streamcloud, streamango, powvideo, gamovideo, etc... and the search engine in these cases would be used to enter the URL that directs you to the video.

**Comment by opusforlife2** [comment]
Closing this due to multiple services being requested. Feel free to open a new issue for each.
