### ISSUE TITLE
Youtube: No video length for age restricted videos

### ISSUE THREAD

**Issue by coffeemakr** [TeamNewPipe/NewPipeExtractor#44]
There is no slider or similar to detect the length of youtube videos with age restriction.
See for example this video: https://www.youtube.com/watch?v=i6JTvzrpBy0

**Comment by theScrabi** [comment]
I see a slider.

**Comment by coffeemakr** [comment]
Interesting does it look different than this https://screenshots.firefoxusercontent.com/images/a2fed9c7-61a4-4b6a-8f40-ed5f5ae68ca2.png or am I just unable to see the slider?

**Comment by theScrabi** [comment]
I see.
O I just noticed I had my youtube video unblocker enabled.

**Comment by wb9688** [comment]
Doesn't happen with yt_new at least.
