### ISSUE TITLE
Search video exception

### ISSUE THREAD

**Issue by virsachi2121** [TeamNewPipe/NewPipeExtractor#449]
when search videos always get below exception

org.schabi.newpipe.extractor.exceptions.ParsingException: Got HTML document, expected JSON response (latest url was: "https://www.youtube.com/supported_browsers?next_url=https://www.youtube.com/results?search_query%3Dcartoni+italiani+2019&gl=TR&pbj=1")
at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getValidJsonResponseBody(YoutubeParsingHelper.java:513)
at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonResponse(YoutubeParsingHelper.java:526)
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.onFetchPage(YoutubeSearchExtractor.java:67)
at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:29)

**Comment by opusforlife2** [comment]
This is an exact copy of #446 by a different username. What's going on?

**Comment by virsachi2121** [comment]
i still have the same exception

**Comment by TobiGr** [comment]
take a look at your URL, or just visit it. You are checking if your browser is supported... The actual search is in the next_url param
Did you pass it to the extractor? I am pretty sure that we do not generate that....

**Comment by virsachi2121** [comment]
this is my exception :

W/System.err: org.schabi.newpipe.extractor.exceptions.ParsingException: Got HTML document, expected JSON response (latest url was: "https://www.youtube.com/results?search_query=ss&sp=EgIQAQ%253D%253D&gl=GB&pbj=1")
W/System.err:     at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getValidJsonResponseBody(YoutubeParsingHelper.java:513)
W/System.err:     at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonResponse(YoutubeParsingHelper.java:526)
W/System.err:     at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.onFetchPage(YoutubeSearchExtractor.java:67)
W/System.err:     at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)

**Comment by virsachi2121** [comment]
I am a beginner, this is the search method in my project : 

 public ListExtractor.InfoItemsPage<InfoItem> doInBackground(String... strArr) {

            ListExtractor.InfoItemsPage<InfoItem> page1 = null;
            final List<String> contentFilters = new ArrayList<String>();
            contentFilters.add(YoutubeSearchQueryHandlerFactory.VIDEOS);
            SearchExtractor extractor = null;
            try {
                extractor = YouTube.getSearchExtractor(strArr[0], contentFilters, "");
                extractor.fetchPage();
                 page1 = extractor.getInitialPage();

            } catch (ExtractionException | IOException e) {
                e.printStackTrace();
            }
            return page1;
        }

**Comment by TobiGr** [comment]
hm. which version are you using?

**Comment by virsachi2121** [comment]
@TobiGr  v0.20.2

**Comment by tadoms** [comment]
Hello Virsachi

**Comment by tadoms** [comment]
Please check your USER_AGENT of DownloaderImpl.

You should update your USER_AGENT as below:
public static final String USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0";
