### ISSUE TITLE
prevent Extractor form fetching

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipeExtractor#45]
I noticed we still fetch data in the constructor of the extractors. We use the [fetchPage()](https://github.com/TeamNewPipe/NewPipeExtractor/blob/master/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java#L89) function for fetching, but I think it would be better if this function would be called manually and not through the extractor.

**Comment by coffeemakr** [comment]
Totally agree. Where would you put it? In `StreamInfo.getInfo(extractor)` ?

**Comment by theScrabi** [comment]
no fetchPage() is ok, but I would leave it to the implementer to call fetch page.
Like in the forntend somewher someone would write this:
```
StreamExtractor ex = new YoutubeStreamExtractor(url);  // only creates extractor
ex.fetchPage(); //actually load data

ex.getSomeData();
...
```
