### ISSUE TITLE
Pls add Bitchute video hosting

### ISSUE THREAD

**Issue by ah1102** [TeamNewPipe/NewPipeExtractor#459]
Please add video hosting Bitchute https://www.bitchute.com . Many bloggers from youtube go there. It is now gaining relevance.

![Снимок экрана 2020-11-07 в 00 20 15](https://user-images.githubusercontent.com/58341369/98439081-2df9e300-2100-11eb-9950-fad8fdaaa4cd.png)

**Comment by Stypox** [comment]
There was a discussion about this already. We will not add BitCute for multiple reasons. You can read them here: https://github.com/TeamNewPipe/NewPipeExtractor/pull/325#issuecomment-626801193

**Comment by ah1102** [comment]
This is political censorship on your part. Real free software developers don't do that low.
