### ISSUE TITLE
[Request] Expose more variables to be able to create dash manifests

### ISSUE THREAD

**Issue by FireMasterK** [TeamNewPipe/NewPipeExtractor#461]
So, I'm trying to use NewPipe in a frontend with videojs, unfortunately, the extractor doesn't provide enough information to create a dash manifest for 1080p playback.

Is there any way to add the following to the VideoStream?

```
itag
codec
width
height
fps
initRange
indexRange
bitrate // different from averageBitrate
```

They are already in the JSON response, and youtube-dl already does this, so I don't see why not.

**Comment by Stypox** [comment]
This will be done when NewPipe will finally get support for playing DASH. Basically this is the releavant PR (will be reopened soon): #367

**Comment by FireMasterK** [comment]
I believe that's a unrelated PR because of the following:

- That PR is involving the parsing of the mpd files
- The following data is available in the parsing of the adaptive streams / videoonly/audio streams, parsing the dash file would be unnecessary in this case

NewPipe solves this issue by using a MergingMediaSource in exoplayer which unfortunately doesn't exist in videojs.

**Comment by Stypox** [comment]
Yeah,that PR is not the ultimate solution, but it's the first step

**Comment by Stypox** [comment]
Closing in favour of #223

**Comment by FireMasterK** [comment]
@Stypox 
Isn't that a totally different issue? This one is related to the adaptiveStreams while that is regarding playback of dash videos.

**Comment by B0pol** [comment]
itag, fps, are already available in ItagItem

**Comment by FireMasterK** [comment]
fps can be inaccurate at times since it's a hardcoded value (from the itag).

In [this video](https://www.youtube.com/watch?v=L8_fTg09XTI), it would show up as 60 fps although it's 50. #488 fixes this already tho.

**Comment by harshmandan** [comment]
@FireMasterK is this issue resolved with you PR?

**Comment by FireMasterK** [comment]
Yes it has, but dash manifest parsing needs to added to finish off everything.

**Comment by opusforlife2** [comment]
Now that DASH support has been added, you can finally make the front-end you wanted! You should call it... "Depip".
