### ISSUE TITLE
Unable to play some youtube videos

### ISSUE THREAD

**Issue by maohieng** [TeamNewPipe/NewPipeExtractor#462]
Hi,
Thank you for this awesome library. I'm using it with one of my application. 
Unfortunately, I have some of my videos that cannot be played in my app :'( :
 - https://youtu.be/nH5DLhTpLzI
 - https://youtu.be/q0Zkir-Nk9k

Can you help solving with these videos?

Thank you,

**Comment by FireMasterK** [comment]
NewPipe doesn't have the ability to parse dash streams, you can use the regular streams - 720p/360p which should work fine.

**Comment by Stypox** [comment]
Closing in favour of #223
