### ISSUE TITLE
Is this possible to get channel name, link and id

### ISSUE THREAD

**Issue by waqarr** [TeamNewPipe/NewPipeExtractor#468]
Is this possible to get(extract) channel name, link, and id from a youtube video id or youtube video link. Thank you so much for the help

**Comment by Stypox** [comment]
Yes, take a look at `YoutubeStreamExtractorTest`s

**Comment by waqarr** [comment]
`
YoutubeStreamExtractor extractor = (YoutubeStreamExtractor) YouTube
                    .getStreamExtractor("https://www.youtube.com/watch?v=f-HPQJZRACI");
            extractor.fetchPage();

extractor.getSubChannelName()
`

this method always provide null/empty

**Comment by waqarr** [comment]
Thank you so much for your help. channel name fetches successfully.
