### ISSUE TITLE
how can i deal with reCaptcha. 

### ISSUE THREAD

**Issue by waqarr** [TeamNewPipe/NewPipeExtractor#471]
on my internet always the exception of ReCaptcha. how can I get ReCaptcha URL and open in webview to resolve it and extract the audio stream? Thank you so much (Any test implementation)

**Comment by Stypox** [comment]
You can take a look at NewPipe's `ReCaptchaActivity` and its usages, where `ReCaptchaException`s are handled, and at NewPipe's `Downloader`, where cookies are set

**Comment by waqarr** [comment]
Thank you so much
