### ISSUE TITLE
[Feature Request] Add stream segments (YouTube)

### ISSUE THREAD

**Issue by vkay94** [TeamNewPipe/NewPipeExtractor#476]
#### What is it
It's a feature request to add segment handling for streams if provided by the service/stream.

#### Is your feature request related to a problem? Please describe it
Since the YouTube service provides timestamp handling in the initial data to navigate to pre-defined timestamps of the video it'd be nice to have included in the extractor so it can be used in NewPipe.

#### How will you/everyone benefit from this feature?
Having an (optional) separate overview of the contents of a stream improves the user experience, especially for longer streams.

#### Implementation
Implementation for YouTube: [Link](https://github.com/vkay94/NewPipeExtractor/blob/ccbfda08b7eacaa4ef1a441e65854c7b83724a14/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L1066-L1114)

Class containing the information for the stream segment: [Link](https://github.com/vkay94/NewPipeExtractor/blob/strean-segments/extractor/src/main/java/org/schabi/newpipe/extractor/stream/StreamSegment.java)

In short: If the stream contains valid data it will be parsed otherwise the method returns an empty list. This also implies to services which don't provide such functionality, they return `Collections.emptylist()`.

I ran some unit test with existing streams and other streams which contain the data. They run without problems. The implementation can be found in this commit: https://github.com/vkay94/NewPipeExtractor/commit/ccbfda08b7eacaa4ef1a441e65854c7b83724a14

#### Test against NewPipe
You can see a very simple implementation for show purposes here: https://streamable.com/e/pzjjjf
Here's a better implementation (inside the player): https://streamable.com/e/3e27wa
Debug apk (description, first video): [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5653543/app-debug.zip)
Debug apk (player, second video): [app-debug-segment-test-02.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5655757/app-debug-segment-test-02.zip)

#### Additional info
Let me know what you think about the implementation itself and whether it's fine for the extractor even if YouTube is the ony 
 service supporting it in the moment.

**Comment by HTSamurai** [comment]
y e s

**Comment by shivasagarrao** [comment]
@vkay94 

> https://streamable.com/e/pzjjjf and https://streamable.com/e/3e27wa

Both links are not working.
