### ISSUE TITLE
Playing downloaded episodes seemlessly in NewPipe

### ISSUE THREAD

**Issue by dewijones92** [TeamNewPipe/NewPipeExtractor#480]
Bit of a tricky one to explain...

Flow:

1. Listen to youtube video inside newpipe (in background mode) - audio only
2. Tell newpipe to download the audio for that video
3. Wait for it to successfully download
4. Put phone in airplane mode
5. **I expect to still be able to continue listening in background mode but NewPipe still tries to fetch the next bits of the audio from youtube.**
Instead I have to go in "Downloads" in newpipe and open in an external app.

Do you think this is a sensible idea?

Many thanks for all your hard work :)

**Comment by dewijones92** [comment]
I meant to post this in https://github.com/TeamNewPipe/NewPipe
woops

**Comment by yashpalgoyal1304** [comment]
hi, pls post the link to the issue here too (:
