### ISSUE TITLE
[FR] YouTube Topic Channels

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipeExtractor#501]
What is actually needed here to support getting content from topic channels? I want to look into it for some time now, but I have no idea where to start.

**Comment by FireMasterK** [comment]
Could you provide an example for a topic channel?

**Comment by kubo6472** [comment]
https://www.youtube.com/channel/UCMU5I9l66nyQOgNqtYuSGPg

**Comment by FireMasterK** [comment]
I see, these channels seems to contain only playlists and have no 'videos'.

We can add support for these by extracting the playlists from the json file.

The first step would probably be to create some kind of structure for these channels in the extractor.

**Comment by Stypox** [comment]
Channel tabs would be the optimal solution

**Comment by TiA4f8R** [comment]
Note also that topic channels / YT Music channels has hidden uploads playlists but they are only accessible with the YouTube API.

**Comment by kubo6472** [comment]
> Channel tabs would be the optimal solution

I like the simple structure, and we're only trying to get videos that are hidden in playlists, or on other channels (See OAC: On YouTube, this channel:  youtube.com/channel/UCKSutkiztiMlYAVyxR5dnVw includes videos from these two channels bc they're part of the official artist channel youtube.com/channel/UC0RQgvoncsNlG64NXgeKjzg youtube.com/channel/UCt7rENovlOO2n_e7WFT8hng) this is hard enough to understand on YouTube itself, not even trying to extract the info from it. Optimally, all videos will be listed like on music.youtube.com (you can visit the latter, second channel I link on there [music.youtube.com/channel/UC0RQgvoncsNlG64NXgeKjzg] and you'll find all of the videos there.) The playlists act like albums, from which the individual videos can be sorted, as you'll find on the bottom of YT Music page. The crosslinking is based on the "main artist" and if artists are featured, then the original video (same URL) can be found on their channel. But when it's linked together (channel no. 1) then on YT music it doesn't use that channel, but rather the topic channel URL. Hopefully, I haven't confused you too much.

**Comment by TiA4f8R** [comment]
@kubo6472 For what I said, here is the upload playlist of the channel you provided: [https://www.youtube.com/playlist?list=UUMU5I9l66nyQOgNqtYuSGPg](https://www.youtube.com/playlist?list=UUMU5I9l66nyQOgNqtYuSGPg)

**Comment by kubo6472** [comment]
Yep, now I remember that there are these "All Uploads" playlists. But that doesn't make the OAC any less complicated.

**Comment by FireMasterK** [comment]
There seems to be some relevant work already in #279

**Comment by AudricV** [comment]
> Note also that topic channels / YT Music channels has hidden uploads playlists but they are only accessible with the YouTube API.

I was wrong, you can get them for every channel (except some YouTube system ones)! You need to take a channel ID, and replace the two first characters (`UC`) by `UU`. Then use the resulting ID as the uploads playlist ID.
