### ISSUE TITLE
Investigate YoutubeSearchQHTest.testRegularValues

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipeExtractor#544]
YoutubeSearchQHTest.testRegularValues runs successfully inside CI, but fails on my local maschine.
Can someone else confirm that that also happens for them?

**Comment by Stypox** [comment]
It works on my end (after un-ignoring it, obviously)

**Comment by XiangRongLin** [comment]
Well...
this too is a problem which occurs on windows and not on linux (WSL).
