### ISSUE TITLE
Scheduled CI run failures due to ReCaptcha

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipeExtractor#547]
A scheduled CI run, which runs against the real webite failed and needs to be investigated

Recaptcha https://github.com/TeamNewPipe/NewPipeExtractor/runs/1923157131?check_suite_focus=true#step:5:291
we cant really do anything about that can we?

**Comment by TobiGr** [comment]
We could add some random sleep time to the test downloader implementation to not make too many tests in a short period.

**Comment by XiangRongLin** [comment]
That would impede with local development by increasing times until getting feedback. So some sort of logic to differentiate between local and CI test would be needed

**Comment by TiA4f8R** [comment]
This doesn't happen (at least for now), as we moved everything to InnerTube and we are only using the website to extract InnerTube's client version and API key. Closing as resolved.
