### ISSUE TITLE
Push CI run failures at YoutubeSearchExtractorTest$ChannelVerified

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipeExtractor#553]
https://github.com/TeamNewPipe/NewPipeExtractor/runs/1929913441#step:5:60

@B0pol `NewPipe.init(DownloaderTestImpl.getInstance())` is used here and needs to be replaced by 
```java
YoutubeParsingHelper.resetClientVersionAndKey();
NewPipe.init(new DownloaderFactory().getDownloader(RESOURCE_PATH + "metaInfo"));
```

**Comment by B0pol** [comment]
you mean verified instead of metaInfo I guess
