### ISSUE TITLE
PR CI job run failures at MediaCCCLiveStreamListExtractorTest.getConferencesListTest

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipeExtractor#563]
https://github.com/TeamNewPipe/NewPipeExtractor/runs/1989145745?check_suite_focus=true#step:5:345
https://github.com/TeamNewPipe/NewPipeExtractor/runs/1989150604?check_suite_focus=true#step:5:345
https://github.com/TeamNewPipe/NewPipeExtractor/runs/1988363647#step:5:345

The changes in the PR did not touch those files which means those tests are unreliable and should be marked as such after they use the `MockDownloader` and #517 is merged

**Comment by TiA4f8R** [comment]
According to the PR linked, it was an issue from mediaccc directly, which has been fixed. If it is still reproducible, please reopen the issue. Thank you!
