### ISSUE TITLE
Add support for Google Podcasts

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipeExtractor#565]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Could you please add Google Podcasts for streaming and downloading podcasts? It's a really amazing website for audio files and podcasts. Please add support for both streaming and downloading podcasts. Subscription and subscription categories are also necessary.

And, yes, support for importing history and subscription from Google Podcasts through Google Takeout will be great.

**Comment by TobiGr** [comment]
Please give us additional info:
- URL to google podcast

**Comment by SameenAhnaf** [comment]
> Please give us additional info:
> 
> * URL to google podcast

https://podcasts.google.com/

**Comment by nikhilCad** [comment]
You can use AntennaPod?

**Comment by opusforlife2** [comment]
The team has revisited the idea of podcast support in Newpipe. Since there are already several great podcast apps, many of them on F-Droid, it has been decided that Newpipe will not be supporting podcasts.
