### ISSUE TITLE
Adjust Page class to incorperate request body

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipeExtractor#569]
With #567 I added a quick fix for the new continuations API. Instead of a GET request with headers and query parameters, now a POST request with the same information inside the request body is necessary. In that PR i just added that made that new custom request right inside the Extractor and passed on the continuations key as the `id` field of `Page`

This needs to be properly done, by also adding a request body field or something similiar to the `Page` class

**Comment by FireMasterK** [comment]
Maybe a Map?

You can technically store everything you need there 🙂

**Comment by Stypox** [comment]
I don't think a map is a good idea, it would make everything more difficult to understand and to test. I'd go with just a new request-body field in the class.

**Comment by XiangRongLin** [comment]
Closed by #599
