### ISSUE TITLE
[EU countries only] YouTube JSON data cannot be fetched due to new EU cookies agreement

### ISSUE THREAD

**Issue by TiA4f8R** [TeamNewPipe/NewPipeExtractor#592]
Google change the way for consent about YouTube cookies agreement in EU countries. Instead of showing a popup in the website, YouTube redirects the user to a new webpage at consent.youtube.com domain. It also affects YouTube JSON fetching data.
Issue seems to be more reproducible now, it's in A/B testing.

Fix for this is to put a cookie `CONSENT` with `YES+` value for every YouTube request, excepting images, video or audios of course.

Or we can also move JSON requests to youtubei.googleapis.com, but all requests are POST (not tested if it works, I am not really sure).

Reported a while ago on Reddit: https://www.reddit.com/r/uBlockOrigin/comments/lz4ibd/new_fullscreen_before_you_continue_to_youtube_page/

**Comment by XiangRongLin** [comment]
@TiA4f8R 
1. Which extractors does this affect? 
2. Can you work on this? For me the app still works as normal, meaning i can't

**Comment by TiA4f8R** [comment]
For now, channels and playlists on my side.
But it affects every request to the website, according to some posts in uBlock Origin subreddit.

**Comment by TiA4f8R** [comment]
> Can you work on this? For me the app still works as normal, meaning i can't

No, I can't, I don't have free time right now.

**Comment by TobiGr** [comment]
I was able to reproduce this. With all choices set to "No", I get this `CONSENT` cookie `YES+cb.20210328-17-p0.de+F+068`. The last three digits change randomly. 
I think we should add proper cookie handling to the downloader, just like in the [DownloaderImpl](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/DownloaderImpl.java). I also do not have time for this

**Comment by B0pol** [comment]
See https://github.com/ytdl-org/youtube-dl/issues/28628 for rejecting tracking

**Comment by B0pol** [comment]
Weirdly some people are not affected by this (and living in EU countries) using NewPipe. We probably should only add the CONSENT cookie if needed, i.e. if redirected to consent.youtube.com

**Comment by TobiGr** [comment]
Can you implement that?

**Comment by B0pol** [comment]
no, i'm not affected, it works fine on my newpipe

**Comment by TiA4f8R** [comment]
Also, NewPipe already get redirects from consent.youtube.com to youtube.com with a additional param, with a cookie CONSENT which has the PENDING+_something_ value. So it's really strange.
