### ISSUE TITLE
Views aren't extracted from YouTube Originals content

### ISSUE THREAD

**Issue by FireMasterK** [TeamNewPipe/NewPipeExtractor#596]
Note: It does not happen when looking at the video directly.
I've seen it on the trending and channel pages.

Example URL: https://www.youtube.com/channel/UCLXo7UDZvByw2ixzpQCufnA or https://piped.kavin.rocks/channel/UCLXo7UDZvByw2ixzpQCufnA

**Comment by AudricV** [comment]
Closing due to https://github.com/TeamNewPipe/NewPipeExtractor/pull/707#issuecomment-1296260408. Note that the change made in this PR has been applied in #1016 due to the NewPipe issue linked in it.
