### ISSUE TITLE
Remove static variables from extractors

### ISSUE THREAD

**Issue by mauriciocolli** [TeamNewPipe/NewPipeExtractor#6]
As I said [here (comment)](https://github.com/TeamNewPipe/NewPipeExtractor/pull/5#issuecomment-296312218), we need to remove these static variables, because (among another reasons) let's say that I want to extract multiple channels at the same time, with the current static variables one "instance" will interfere with the other, not pretty...

[Here](https://gist.github.com/mauriciocolli/8ac78739bc4b316f6a947f3cc3ce52ea)'s a gist demonstrating that.

PS: Another problem is that you can't request a specific page from a channel, but let's fix that after this is fixed.

**Comment by mauriciocolli** [comment]
@theScrabi I was thinking, does the page number in channel extractor make sense? 

Because there some bad things that it brings (despite that currently, it doesn't work at all):
- You don't know how many pages there are
- Some sites like YouTube doesn't have pages (I don't know one that have), it works as the user demand more videos (scroll all the way down)
- I don't see a very clear use case for page number, maybe continue where you stop (but anyway, that's more complex/difficult to implement in services that don't have the concepts of pages, because you would have to keep loading the on demand urls, until you get to the "page")

So, wouldn't make more send implement it that way, on demand?

**Comment by theScrabi** [comment]
## Introduction to the problem

That page thing is indead a problem. I've tried to implement the NewPipe backend like a slingle state machine, like regular REST Api are set up. However a Website is not a single state machine, as you can see on this example. Sending one and the same url will give you a different output (multiple states).
This might be a flow of NewPipe, and it might also cause some trouble later on when we implement different services.

## Concrete Problem
At the moment it works like this: Every request is a new Instance of the back end. So the back end does not remember anything from the last request (it does not remember it's state). This is why the page parameter has to be given to the back end, so it's possible for the front end to remember the state.

In our case the data send from youtube is not the same for every url (one time its html one time it's ajax with less information). That means that NewPipe has to simulate a stateless machine, and that's bad you  are right. 

## What we need
Well I don't want to say it but It might be that the backed as it is designed at the moment will cause trouble. The extractor/collector thing
1. is bad for parallelization
2. requires all information to be given at every point of time

## Solution
I see two solutions:
1. Make an instance of the back end that lives as long as the channel/video/bla is displayed
2. Do not collect all the data, but make the frontent reside what it needs.

What do you think?

**Comment by mauriciocolli** [comment]
I think the instance living as long as it's used, is good for me (at least for now, I'll think more about it).

And I'm doing a **big** refactor in the extractor (I implemented the "on-demand", as I discussed in the previous post), take a look at: https://github.com/mauriciocolli/NewPipeExtractor/tree/refactor-extractor

Also I want to implement the playlist asap too, but I want to, at least, get rid of these issues, as it suffers the exact same problem as the `ChannelExtractor` (copied the same code).

**PS**: Please take a look at those open pull requests.

**Comment by theScrabi** [comment]
"On-demand" means you are not pulling out all the data into a struct, but calling the required function when data is needed right?

**Comment by mauriciocolli** [comment]
I'm doing that **_only_** in the `getNextStreams`, because it makes sense, there's no point in getting "more videos" if the user doesn't demand it.


> 2. Do not collect all the data, but make the frontent reside what it needs.

> "On-demand" means you are not pulling out all the data into a struct, but calling the required function when data is needed right?

Can you explain a little more about this? 

I don't think it's necessary to the other fields being "on-demand" too, because if you download the page, you already have all the information, and if you need any one of them (view count, video title, uploader), you'll have to download all the page anyway.

Or do you mean download only when the user want to, like `fetchPage` or `startExtraction`?
