### ISSUE TITLE
Bandcamp audio plays at half-speed

### ISSUE THREAD

**Issue by micheal65536** [TeamNewPipe/NewPipeExtractor#606]
When playing a song on Bandcamp, the song plays at half speed (and is an octave lower in pitch). I have tried this with 3 different songs from 2 different artists. My device has a mono speaker and I suspect that this may be related, although the same issue occurs when I use the headphone output.

**Comment by TobiGr** [comment]
Are you sure that this is extractor related? What player are you using? Is it NewPipe? if that is the case, we might want to transfer the issue into the correct repository.

**Comment by micheal65536** [comment]
I'm playing it in NewPipe (no external player). Now that I think about it, I don't know for sure that it's extractor related. I've never had it occur with YouTube though, so if it isn't a bug in the extractor then it would still seem that the Bandcamp extractor is doing something different in a way that the NewPipe app doesn't like.

Is there a good way to test/determine if it's the extractor or the app? Should I try the download option in NewPipe? Should I try using an external player?

**Comment by micheal65536** [comment]
I just discovered that the playback speed in NewPipe was set to 0.5x. I reset it to 1.0x and Bandcamp audio is now working fine.
