### ISSUE TITLE
Create instances of StreamingServices on the front end.

### ISSUE THREAD

**Issue by wojcik-online** [TeamNewPipe/NewPipeExtractor#62]
Would it be possible to create instances of the `StreamingService`s on the front end and pass them to the extractor via function call?
This would have several advantages:

 - It would eliminate the need for the awkward `ServiceList` enum. Is the following a list of services or a single service?
    ```java
     ServiceList serviceItem;
    ```

 - It would give the front end a proper way to obtain instances of the `StreamingService`s.
The constructors should take all parameters necessary to create a particular service.
This would allow the front end to store settings of the services. For example YouTube might take information about the language in order to parse relative dates.

 - It would allow for services to be implemented outside of this project which would be extremely useful for those who want to use the `NewPipeExtractor` as a library.

How this idea could be implemented:
```java
public class NewPipe {
    private static final Map<Integer, StreamingService> registeredServices = new HashMap<>();

    public static void registerService(StreamingService service) {
        // TODO
    }
}
```

**Comment by theScrabi** [comment]
Well. This is not how NewPipe was intended. The extractor should be an aggregate of several services. This would break the idea of it.
