### ISSUE TITLE
Fix failing tests related to unavailable content

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipeExtractor#632]
Fix tests that were ignored by #631 

https://github.com/TeamNewPipe/NewPipeExtractor/blob/3a3ade20f48cf37526eb970a7df56ee2405125fc/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L802 throws a NPE because `videoInfoPage.get("player_response")` return null

**Comment by Imericxu** [comment]
I think could be combined with [Issue#6342](https://github.com/TeamNewPipe/NewPipe/issues/6342), which contains a crash log of this issue.
