### ISSUE TITLE
YouTube Comments isUploaderVerified always false

### ISSUE THREAD

**Issue by FireMasterK** [TeamNewPipe/NewPipeExtractor#636]
Example Usage: https://github.com/TeamPiped/Piped-Backend/blob/bdfd86774049fe015814e24f05b6376b21e06531/src/main/java/me/kavin/piped/utils/ResponseHelper.java#L407

Example: https://piped.kavin.rocks/watch?v=gMjpG-vQkpQ

It looks like the mobile website has changed - there is no longer a check mark to see if the commenter is verified.

**Comment by B0pol** [comment]
It hasn't changed, it was always false. See https://github.com/TeamNewPipe/NewPipeExtractor/blob/1ff56a85df323a86d5d90b78132c0e57b90e9154/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsInfoItemExtractor.java#L128-L131

**Comment by mhmdanas** [comment]
Since this has always been the case, I'll be closing this issue.
