### ISSUE TITLE
Use 0p as audio track

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipeExtractor#648]
0p is currently added as video track. It should be added as audio track

Example video: https://framatube.org/videos/watch/d6bba4fa-b67f-4e27-be4f-bb5406dc5159

See https://github.com/Chocobozzz/PeerTube/issues/3281

**Comment by TiA4f8R** [comment]
@albjeremias You don't have to try to fix something, they will be extracted with my PR: #663.
However, their bitrate will be not available, because a separate request will be needed to get metadata like this (or a change in PeerTube video JSON API).

**Comment by opusforlife2** [comment]
> However, their bitrate will be not available, because a separate request will be needed 

Still the case?
