### ISSUE TITLE
The watch count of LIVE streams is treated as the upload date.

### ISSUE THREAD

**Issue by wojcik-online** [TeamNewPipe/NewPipeExtractor#67]
While working on #61, I've come across this bug of the YouTube service:
The watch count of LIVE streams is treated as the upload date. This doesn't matter if the date is just displayed, but the relative time parser fails.
This happens on the channel page and on the feed and in related videos under another stream. The bug is most likely in the `YoutubeStreamInfoItemExtractor`.
```
org.schabi.newpipe...ParsingException: Unable to parse the date: 103,985 watching
  at org.schabi.newpipe...TimeAgoParser.parseTimeUnit(TimeAgoParser.java:80)
  ...
```

![liveyt](https://user-images.githubusercontent.com/35582382/35882905-e2000cb4-0b85-11e8-86ee-3bc3217cb87a.png) ![livenp](https://user-images.githubusercontent.com/35582382/35882903-e1ddf32c-0b85-11e8-82cb-696f6087e391.png)
Everything look right in the pictures, but the watch count is actually omitted (by `if (infoItem.view_count >= 0)`) and the _103,985 watching_ is the upload date.

**Comment by wb9688** [comment]
Doesn't happen with yt_new at least
