### ISSUE TITLE
BiliBili Support

### ISSUE THREAD

**Issue by CreatorZZY** [TeamNewPipe/NewPipeExtractor#674]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I think it would be nice if you add feature Bilibili support which makes watching bilibili in newpipe possible.

[BILIBILI WEBSITE](http://www.bilibili.com)

[Utils](https://github.com/ZimoLoveShuang/bilibili-video-analysis)

#### Is your feature request related to a problem? Please describe it
Because it is better if I can watch both bilibili and Youtube In Newpipe. And Bilibili actually do bad in their html5 player.
it is also better if i can group the group of the channal for the big number of the group i have when bilibili is support but even now.

#### Additional context

Note that: Distinguish the tag and group of the channel. Channals have to be in a group but It can be in muti-tag. (Tag is similar to the group in newpipe nowaday.)

#### How will you/everyone benefit from this feature?
It will be convenient for all people who want to learn about Chinese culture through bilibili.

**Comment by InfinityLoop1309** [comment]
It stuck there for months. Is it approved but no one do this yet? If so, I am going to add this support.

**Comment by InfinityLoop1309** [comment]
**How will you/everyone benefit from this feature?**

Bilibili itself is the most popular stream service in China, even more popular than Tiktok. Because of the censorship, Youtube is banned in China, so most Simplified Chinese is only available in Bilibili.

**Comment by CreatorZZY** [comment]
Respect !!!


> **About this service**
> 
> Bilibili is a video on demand platform similar to YouTube but for the Chinese market primarily. IT's operated by a company in China. It does have a global version, too, but it's not very well known outside China. The video categories are the same, they host music videos, let's plays, pretty much anything YouTube also provides. It has a few 10 million users. It's one of the major streaming platforms within China. People use it there because YouTube is banned.
> 
> **How will you/everyone benefit from this feature?**
> 
> Bilibili itself is the most popular stream service in China, even more popular than Tiktok. Because of the censorship, Youtube is banned in China, so most Simplified Chinese contents are only available in Bilibili.
> 
> **Additional context**
> 
> I am willing to maintain this for long time.

**Comment by InfinityLoop1309** [comment]
I have made a fork [NewPipeWithMoreServices](https://github.com/InfinityLoop1309/NewPipeWithMoreServices) which includes Bilibili service and it works well.

**Comment by CreatorZZY** [comment]
Would you like to merge your work to the official repo branch?

**Comment by InfinityLoop1309** [comment]
> Would you like to merge your work to the official repo branch?

Unfortunately, no (and not possible) as my code does not satisfy their commit policy.

**Comment by opusforlife2** [comment]
Commit policy?

**Comment by opusforlife2** [comment]
BTW: It seems like I missed my GH notification about this, sorry. The team has decided to reject Bilibili, mainly due to censorship concerns.

Thank you for creating the fork, though. We can redirect users towards it when needed. 👍
