### ISSUE TITLE
niconico

### ISSUE THREAD

**Issue by Zehra** [TeamNewPipe/NewPipeExtractor#719]
Video streaming site mostly specific to Japan.
It would be a nice addition as it offers a great deal of community based content and may be of interest to those learning the Japanese language.

Homepage: [www.nicovideo.jp](https://www.nicovideo.jp/)
Edit: Added link to niconico homepage.

**Comment by AioiLight** [comment]
I'm trying to add support for Niconico.
![Screenshot_1641290666](https://user-images.githubusercontent.com/13918537/148043162-cef95d75-f0db-4962-a6bf-37d6737fc47d.png)
![Screenshot_1641290804](https://user-images.githubusercontent.com/13918537/148043169-d6345e88-d675-4927-8e12-ff1f8e9d0a9d.png)

I will send PR to repo if I reached good quality.

**Comment by opusforlife2** [comment]
Status update: this service has been rejected by the team.

**Comment by opusforlife2** [comment]
Largely because all the team members are busy, and do not have the time to go through the lengthy process involved in the addition of an entire new service, especially one they will not be using themselves.

**Comment by selurvedu** [comment]
@opusforlife2 got it, thanks for answering!
