### ISSUE TITLE
Jitpack release for 0.21.10 failed

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipeExtractor#728]
If you look at https://jitpack.io/#TeamNewPipe/NewPipeExtractor you can see that the the build for 0.21.10 failed.

I created an issue with JitPack: https://github.com/jitpack/jitpack.io/issues/4731

@TobiGr @Stypox

**Comment by TobiGr** [comment]
fixed by deleting the version from jitpack.io and rebuilding it.
