### ISSUE TITLE
Rumble and Odysee

### ISSUE THREAD

**Issue by foolkiller1999** [TeamNewPipe/NewPipeExtractor#736]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
 would love to see more sources like rumble and odysee

#### Why do you want this feature?

For the videos censored by YouTube that can only be found on rumble and odysee.

**Comment by mhmdanas** [comment]
For Odyssee, see #434. Please edit your request to mention Rumble only (also put the home page URL in the issue body please).
