### ISSUE TITLE
Upload on play store

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipeExtractor#737]
Im working on making a music streaming app using the newpipe extractor...I wanna know if I can use this Library in my app and remove some features like downloading songs...and only use streaming as the main thing..would Google take down my app?
It would play only the music,the video will not be shown

**Comment by mhmdanas** [comment]
Try it; nothing to lose. :)

Seriously though, if you're going to stream from YouTube, it still goes against their ToS, regardless of whether you add downloading or not (I believe they require ads to be shown in their ToS). Please take this with a grain of salt do your own research though; I'm not going to go through those pages of legalese. ;)
