### ISSUE TITLE
Get related or next items, like in youtube music.

### ISSUE THREAD

**Issue by Yamzst** [TeamNewPipe/NewPipeExtractor#748]
I can get related items from a youtube video.
```
val extractor = ServiceList.YouTube.getStreamExtractor(url)
extractor.fetchPage()
for (song in extractor.relatedItems!!.items) {
.....
 }
```
However, if we test with music videos, the related items you get are different than what Youtube Music can get.

In other words, Youtube Music does a better job of getting music videos related to the main one.

For examples you can use:

`YouTube.getSearchExtractor(query, singletonList(YoutubeSearchQueryHandlerFactory.MUSIC_SONGS), "")`

To get items like in Youtube Music.

 You could do something like this, for the related items.

**Comment by TiA4f8R** [comment]
This would require adding a separate YouTube Music service. Merging your request into the service support issue (#614).

Thank you!
