### ISSUE TITLE
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get audio streams

### ISSUE THREAD

**Issue by SufyanQadeer** [TeamNewPipe/NewPipeExtractor#765]
Attempt to invoke virtual method **'java.lang.String org.schabi.newpipe.extractor.stream.AudioStream.getUrl()'** on a null object reference

**Comment by XiangRongLin** [comment]
Can you please provide information with which the issue can be reproduced. With the current information nothing can be done.

**Comment by TiA4f8R** [comment]
Closing as stale. If you are still getting the issue, please let us know and provide more details, such as the complete stacktrace and how you are using the extractor in your client(s). Thank you.
