### ISSUE TITLE
add gogoanime

### ISSUE THREAD

**Issue by mobilex1122** [TeamNewPipe/NewPipeExtractor#773]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

add gogoanime as one of sources.

#### Why do you want this feature?

I like new pipe because it has almost every source I use (youtube, soundcloud) but I also using gogoanime so that why I'm posting this. (it might not be possible to do because of the problems with funimation)

**Comment by litetex** [comment]
Transferred the issue 😉

**Comment by Atemu** [comment]
This is not a legal service.

**Comment by mobilex1122** [comment]
Got it. I thought that it wouldn't be possible.

**Comment by litetex** [comment]
> This is not a legal service.

Based on what facts...

**Comment by Atemu** [comment]
I don't believe they hold a license for almost every halfway relevant Anime in existence.

**Comment by litetex** [comment]
> I don't believe they hold a license for almost every halfway relevant Anime in existence.

Based on what facts...

**Comment by litetex** [comment]
> Mate, have you seen the site?

Either you argue with facts (more than one sentence) or you just stop.
Just by taking a look at the site I don't know if the content is legal or not.

Maybe you could quote a source that explains a bit more or put in a list that why it's illegal.

Anyway found a relative good "article" here https://www.quora.com/Is-GoGoAnime-legal that summarizes the problems, it states:
* Contains 18+ ads
* Contains ads that spread malware
* Contains massive copyright violations
* Very bad privacy policy

→ Rejected
