### ISSUE TITLE
YouTube comments count

### ISSUE THREAD

**Issue by tsiflimagas** [TeamNewPipe/NewPipeExtractor#776]
It would be nice if comments count in YouTube videos (perhaps this could be done for other services too, I just only use yt) could be extracted, so displaying it in the app could then be implemented.

**Comment by opusforlife2** [comment]
This is a UI feature request. So you should open an issue in the NP repo, where the `requires extractor change` label can be applied to it.

**Comment by TiA4f8R** [comment]
Closing in favor of #793.
