### ISSUE TITLE
Separate CI + test for hardcoded SoundCloud client ID

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipeExtractor#781]
As clarified here: https://github.com/TeamNewPipe/NewPipeExtractor/pull/777#issuecomment-1021422300, it is possible, but needs time and effort.

Benefit: CI will stop failing on unrelated PRs because of an outdated client ID.

**Comment by XiangRongLin** [comment]
Just some ideas for solutions
- https://howtodoinjava.com/junit5/junit5-test-suites-examples/
- https://www.baeldung.com/junit-filtering-tests
