### ISSUE TITLE
Question: Rewrite extractor in other languages

### ISSUE THREAD

**Issue by knnhcn** [TeamNewPipe/NewPipeExtractor#801]
By using NewPipe day by day I recently started to get more into the code how everythnig works and stumbled upon the NewPipeExtractor repository. The current license is GPL V3 which forces, besides many other things, modificationsof this repositorys' code to be GPL V3 aswell. However, I was wondering how a complete rewrite of this repository in Swift or TypeScript would be handled. Is this also considered modification and has to be GPL V3 aswell?

Thanks in advance!

**Comment by mhmdanas** [comment]
Can you clarify what "re-write" means?

**Comment by knnhcn** [comment]
Hi @mhmdanas, thanks for the reply.

I would like to know both actually. If they are different or are handled same. But I could imagine to first translate it line by line (if possible) and then taking inspiration.

**Comment by mhmdanas** [comment]
I don't really know the answer to be honest. However, I'd like to know why you don't want to license your re-write under GPLv3. Do you mind sharing the reason?

**Comment by knnhcn** [comment]
Hey @mhmdanas, thanks for the reply.

> I don't really know the answer to be honest. However, I'd like to know why you don't want to license your re-write under GPLv3. Do you mind sharing the reason?

I was just curious if a translate to another programming language counts as modification and therefore has to be licensed under the same license.

> Just found this, it may answer (part of) your question: https://www.gnu.org/licenses/gpl-faq.html#TranslateCode

This actually answers my question. To summarize, a translate of the extractor must also have GPLV v3 license.

**Comment by selfisekai** [comment]
Hi, I'm currently working on reytan, a similar project in Rust (as a part of a larger project) - I haven't published it yet, and it's gonna need more work, but I already have the YouTube video extractor mostly working and getting successfully parsed to a universal data structure. I think it should be fairly easy to add Node.js/TypeScript bindings for that with [Neon](https://neon-bindings.com/), though I think this issue/repo is not the place to discuss that

**Comment by mhmdanas** [comment]
@knnhcn since your question was answered, I'm closing this issue. Feel free to make a comment if you have further questions.
