### ISSUE TITLE
Test failure stack traces really really long

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipeExtractor#803]
When some test in a CI fails, we get hundred-lines long stack traces where the only really useful line(s) are those starting with `org.schabi.newpipe.`, for example check out [this CI](https://github.com/TeamNewPipe/NewPipeExtractor/runs/5278840282). The gradle stack trace for when tests fail is also really really long, almost 400 lines. Is there any way to reduce any of these stacktraces or to filter out useless lines? This is a really minor issue, but I wanted to point it out anyway

**Comment by XiangRongLin** [comment]
My guess would be the `--stacktrace` flag in the command https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/.github/workflows/ci.yml#L38

**Comment by Stypox** [comment]
I found out we can reduce the stack trace by adding the following code inside the `test {}` in `extractor/build.gradle`:
```gradle
    testLogging {
        exceptionFormat = 'short'
    }
```
It turns stacktraces of errors from:
```stacktrace
YoutubeStreamExtractorDefaultTest$StreamSegmentsTestMaiLab > testStreamSegmentsCount() FAILED
    java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "panelIdentifier" is null
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getStreamSegments(YoutubeStreamExtractor.java:1279)
        at org.schabi.newpipe.extractor.services.DefaultStreamExtractorTest.testStreamSegmentsCount(DefaultStreamExtractorTest.java:405)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      // OTHER 89 INTERNAL LINES
        at java.base/java.lang.Thread.run(Thread.java:833)
```
to:
```
YoutubeStreamExtractorDefaultTest$StreamSegmentsTestMaiLab > testStreamSegment() FAILED
    java.lang.NullPointerException at YoutubeStreamExtractorDefaultTest.java:363
```
This is not good, since much information is lost. I also tried the [`stackTraceFilters` method of `testLogging`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/logging/TestLogging.html#stackTraceFilters-java.lang.Object...-) but it doesn't seem to do anything
