### ISSUE TITLE
NPE on getErrorMessage()

### ISSUE THREAD

**Issue by mmin18** [TeamNewPipe/NewPipeExtractor#81]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
     at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.getErrorMessage(YoutubeStreamExtractor.java:517)

    public String getErrorMessage() {
        String errorMessage = doc.select("h1[id=\"unavailable-message\"]").first().text();

videoId: -97j9dP7SKU

**Comment by theScrabi** [comment]
great thanks :)

If you are already on it could you please fix it :D

**Comment by CWftw** [comment]
Frequently seeing this exception. Even if the regex is not right it would be nice if it still did not crash when first() returns null. Something like this:

CWftw/NewPipeExtractor@38665cb6d07d39f62451856b2c9ee765b211f01a

**Comment by AudricV** [comment]
The issue doesn't seem to be present anymore and was probably fixed when we switched to YouTube's JSON "pbj" internal API.

Closing as fixed.
