### ISSUE TITLE
is lib working on AamzonFireTv

### ISSUE THREAD

**Issue by since85stas** [TeamNewPipe/NewPipeExtractor#812]
Trying to use library on amazon FireStick(FireOs 6.2.8.1), and i can't get youTube link. 
There is not response after val `info = NewPipeService.get().getStreamInfoByVideoId(id)`

**Comment by litetex** [comment]
As far as I know it should work on every compatible JVM including the one inside FireOS (which itself is an Android derivative) just like NewPipe does.

**Comment by mhmdanas** [comment]
It's as @litetex says. There's probably some other issue with your code.
