### ISSUE TITLE
Mix-Playlist extraction is broken in EU

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipeExtractor#820]
Currently the Mix-Playlist extraction is broken (looks like YT changed something).
Test returns:
```
Could not get playlistData
org.schabi.newpipe.extractor.exceptions.ExtractionException: Could not get playlistData
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeMixPlaylistExtractor.onFetchPage(YoutubeMixPlaylistExtractor.java:100)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeMixPlaylistExtractorTest$ChannelMix.setUp(YoutubeMixPlaylistExtractorTest.java:356)
	...
```

**Comment by TiA4f8R** [comment]
Seems like you cannot get mixes anymore if you don't consent to tracking (`CONSENT` cookie with a value starting with `YES+`)...

**Comment by opusforlife2** [comment]
Not an issue in India, at least. Likely an EU thing. Maybe we should get someone from another non-EU country to confirm.

**Comment by vludax** [comment]
I see in https://github.com/TeamNewPipe/NewPipeExtractor/pull/600 we added a PENDING consent cookie to certain requests that seem to rely on it. While using a PENDING value against the mix playlist API doesn't seem to resolve this issue, using a `YES` value does work as @AudricV pointed out above. Would that be the right solution here? I'd be happy to create a PR to do that.
