### ISSUE TITLE
Add Podcast RSS Supoort

### ISSUE THREAD

**Issue by wepache** [TeamNewPipe/NewPipeExtractor#824]
It would be great if Podcast RSS support would be integrated. It'd be nice to see all my favorite long form content with the rest of my YouTube videos.

**Comment by Duderine** [comment]
I'm in agreement

**Comment by opusforlife2** [comment]
What does this have to do with the NewPipe Extractor?

**Comment by Duderine** [comment]
> What does this have to do with the NewPipe Extractor?

I don't get it either, but apparently someone opened this issue on the normal new pipe forum and the staff asked to open it here

**Comment by Duderine** [comment]
BTW, I'm in total agreement. RSS support or even Google podcasts repository, it would make the app incredible complete

**Comment by opusforlife2** [comment]
> apparently someone opened this issue on the normal new pipe forum and the staff asked to open it here

Link?

**Comment by wepache** [comment]
I apologize if this is not the correct place to add this feature request.

**Comment by Duderine** [comment]
> > apparently someone opened this issue on the normal new pipe forum and the staff asked to open it here
> 
> Link?

https://github.com/TeamNewPipe/NewPipeExtractor/issues/565#issuecomment-787035165

**Comment by Duderine** [comment]
Also I've requested the same thing 3 days ago and it was fastly closed/refused

https://github.com/TeamNewPipe/NewPipe/issues/8732

**Comment by opusforlife2** [comment]
The team has revisited the idea of podcast support in Newpipe. Since there are already several great podcast apps, many of them on F-Droid, it has been decided that Newpipe will not be supporting podcasts.
