### ISSUE TITLE
Feature request: integrate the return youtube dislikes lib

### ISSUE THREAD

**Issue by finete** [TeamNewPipe/NewPipeExtractor#849]
Currently new pipe does not show the dislikes of videos.
A nice feature would be and integration of the return youtube dislikes repo.

It’s a JS based library, so maybe the two services could communicate via REST or other communication protocol?

I didn’t find a corresponding issue [v]

**Comment by TiA4f8R** [comment]
This will probably not happen because of the current state of the service's back-end code (closed source): see TeamNewPipe/NewPipe#7469 for more details.

Closing as wontfix.
