### ISSUE TITLE
Great preview of the video

### ISSUE THREAD

**Issue by Legoks** [TeamNewPipe/NewPipeExtractor#853]
Add the ability to to enlarge the preview of videos on the home screen
![Screenshot_20220527-230307](https://user-images.githubusercontent.com/104249296/170777442-564736b0-af3b-4d98-8421-cf15b6038b2e.jpg)
![Screenshot_20220527-230233_NewPipe SponsorBlock](https://user-images.githubusercontent.com/104249296/170777460-be5f7331-45e4-4d31-8115-1fa31dc0b0a7.jpg)

**Comment by TiA4f8R** [comment]
Wrong repository.
