### ISSUE TITLE
Need help adding SoundCloud support again

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipeExtractor#89]
@wb9688 I am currently deep refactoring the search part of the NewPipe extractor. The Search engine was some sort of prototype of the later coming ListExtractors. They are more advanced, and fit better into the architecture which is why I wanted to get rid of the search engine. However I am currently trying to focus on supporting Youtube, with the time I have I don't know if I can also add support for SoundCloud. In order to not have to take care about SoundCloud right now I am going to __remove__. If the development is done we can add it again, though I would like to aks you for help.

**Comment by wb9688** [comment]
Remove what? The whole SoundCloud directory? I'd then just remove the
SoundCloud search engine and return null in SoundCloud's main file. I'll
implement the SoundCloud search engine again then (if I've time, which can
be an issue as you know).

**Comment by theScrabi** [comment]
Ok, yes I removed the whole folder, however I will see maybe I can upgrade soundcloud as well :)

**Comment by theScrabi** [comment]
Endwarning SoundCloud is in the race again :) I am almost through. Only tests are missing.

**Comment by wb9688** [comment]
OK, nice!
