### ISSUE TITLE
Suggestion: Use Retrofit for HTTP requests.

### ISSUE THREAD

**Issue by Isira-Seneviratne** [TeamNewPipe/NewPipeExtractor#896]
[Retrofit](https://square.github.io/retrofit/) is a HTTP client where REST APIs can be declared as interfaces, and has support for type converters such as [Moshi](https://github.com/square/moshi/) (JSON) and [jspoon](https://github.com/DroidsOnRoids/jspoon) (HTML). Using it would allow the code for making the requests to be simplified.

@AudricV @Stypox What do you think?

Edit: I've created a sample pull request [here](https://github.com/TeamNewPipe/NewPipeExtractor/pull/898).

**Comment by plotomea0** [comment]
ccc.moneymaster-salvador-jose-sanchez.08-15-1982.http.txt.inc.template.delete.htnp.template-delete-data-api.txt.inc.htnp.template-delete

**Comment by plotomea0** [comment]
> ccc.moneymaster-salvador-jose-sanchez.08-15-1982.http.txt.inc.template.delete.htnp.template-delete-data-api.txt.inc.htnp.template-delete

Has worked

**Comment by Stypox** [comment]
But the downloader has to be specified by clients using NPE, not by NPE itself

**Comment by Isira-Seneviratne** [comment]
Also, Retrofit requires API level 21, as it relies on OkHttp. Will that be a deal-breaker for this particular proposed change?

**Comment by SC1040-TS2** [comment]
> Also, Retrofit [requires](https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-270-2019-12-09) at least API level 21, as it relies on OkHttp. Will that be a deal-breaker for this particular proposed change?

Not since the app version 0.24.0 made it the new minSDKVersion, but who knows?

**Comment by Isira-Seneviratne** [comment]
> > Also, Retrofit [requires](https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-270-2019-12-09) at least API level 21, as it relies on OkHttp. Will that be a deal-breaker for this particular proposed change?
> 
> Not since the app version 0.24.0 made it the new minSDKVersion, but who knows?

Since some apps using the extractor are targeting Android versions below 5.0, I  downgraded the required dependency versions in the PR I created.

**Comment by AudricV** [comment]
Suggestion rejected: see https://github.com/TeamNewPipe/NewPipeExtractor/pull/972#issuecomment-1320991487. Closing.
