### ISSUE TITLE
I noticed this also happens in older versions of official clients, and it's quite random. So YouTube is probably rolling out some sort of update.

### ISSUE THREAD

**Issue by plotomea0** [TeamNewPipe/NewPipeExtractor#897]
I noticed this also happens in older versions of official clients, and it's quite random. So YouTube is probably rolling out some sort of update.

For those who haven't seen yet: https://support.google.com/youtube/answer/12318250?hl=en-US

Similar issues:
https://github.com/iv-org/invidious/issues/3230

_Originally posted by @LuanRT in https://github.com/TeamNewPipe/NewPipe/issues/8713#issuecomment-1200327579_

**Comment by sseodate** [comment]
Yeah me too
