### ISSUE TITLE
[YouTube] Trending is empty sometimes

### ISSUE THREAD

**Issue by FireMasterK** [TeamNewPipe/NewPipeExtractor#899]
On YouTube, NewPipeExtractor returns an empty array of `relatedItems`.

This affects both Piped and even NewPipe.

<img src="https://user-images.githubusercontent.com/20838718/185160559-dc88ce13-bfc9-4c2f-8b24-29b606849c29.png" width="300px" alt="Screenshot_20220817-195413_NewPipe">

**Comment by AudricV** [comment]
YouTube is A/B testing a new format data. When updating mocks of a PR, I got the chance to get this new format data!

The access to the trending data tab content is still the same:

`contents` -> `twoColumnBrowseResultsRenderer` -> `tabs` -> `tabRenderer` -> `0` -> `content`

The old model is:

`sectionListRenderer` -> `contents` -> `itemSectionRenderer` -> `contents` -> `0` -> `shelfRenderer` -> `content` -> `expandedShelfContentsRenderer` -> `items`

The new one is:

`richGridRenderer` -> `contents` -> `richItemRenderer` -> `content`

Inside each model, we have `videoRenderer`s, which can be already extracted as `StreamInfoItem`s with `YoutubeStreamInfoItemExtractor` objects.

Note: this new model contains `richSectionRenderer`s, which are for trending shorts and for the recently trending section, which in contains some of the normal trends.

This new model has so the benefits to only extract the real trending data (limited to the 50 first videos, contrary to the official API which can get up to 200 videos, but that's the same result on YouTube specific trendings (Music, Gaming, Movies)).

**Comment by AudricV** [comment]
Here is the new UI for reference (sorry for the light theme, I prevented YouTube to store cookies in order to be able to get the new UI easier):

<img src="https://user-images.githubusercontent.com/74829229/187042602-e4779284-6803-449e-bd9e-860d689cca1e.png" width="700px" alt="YouTube_FR_new_trending_UI">
