### ISSUE TITLE
YouTube is still broken 

### ISSUE THREAD

**Issue by degarb** [TeamNewPipe/NewPipeExtractor#906]
23.1 has not worked with YouTube for 2 weeks.

I like to have NewPipe and Bravenewpipe installed because Android rolls the dice and scrambles the 50 possible programs that I can share a video with.    With 2 programs,  I double the chances that I will see one of the two,  and save myself a lot of time,  since I use these two programs to download the audio (and sometimes the video)  of something like 600 videos per month, to listen to at work.   I also share about 120 videos to the video player per month on top of watch later list,  before I go to bed.

This is why I am anxious to get the 23.2, youtu.be fixed,  version of Bravenewpipe in addition to the working 23.2 NewPipe.   It will save me a great bit of time over the next month.

I never successfully compiled any program other than basic and aitohotkey.  I can barely find the apks in github,  as the entire github concept seems alien to me,  despite doing a github tutorial.   So,  it is unlikely that I can grab working NewPipe code,  and then, paste it into bravenewpipe,  then compile it--the most likely 15 minute fix.

**Comment by degarb** [comment]
Of course,  it also would be incredible if NewPipe had a setting to put it at the top of the 75 other possible programs to share a youtube link to!!!   At least in the top 4.

I have tried several 3rd party share programs on the playstore, but they all were garbage and made sharing harder overall, or didn't do the job.

**Comment by opusforlife2** [comment]
Wrong repo. This is the Extractor, not the app.
