### ISSUE TITLE
Android 6 compatibility

### ISSUE THREAD

**Issue by vjoomens** [TeamNewPipe/NewPipeExtractor#921]
Hi, I'm having issues with the latest version not being compatible with Android 6 / java 7, with the use of classes like Optional.
Can this be fixed?

**Comment by AudricV** [comment]
See the README:

> To use NewPipe Extractor in projects with a `minSdkVersion` below 26, [API desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) is required.

Below Android API 26, you must use API desugarging in your app.
