### ISSUE TITLE
Export NewPipe playlists to YouTube from the app

### ISSUE THREAD

**Issue by sobornostea** [TeamNewPipe/NewPipeExtractor#923]
Hello !

Would it be possible to export NewPipe playlists as YouTube playlists from the app ? This could be useful to share a playlist to friends and such.

I've managed to do that manually from a db export, here's how I did :
* I got all the URLs from the playlist in the db export (simple SQLs manipulation)
* I extracted the ids `?v` in the URL
* I then added them all to this URL as a comma separated list :
`https://www.youtube.com/watch_videos?video_ids=id1,id2,id3,[...],idn`
* Opening this URL leads me to the playlist

I have limited Java proficiency, but I'll be interested in implementing this feature given some help.

**Comment by opusforlife2** [comment]
Hey there. This is the Extractor repo. You're looking for the app repo.
