### ISSUE TITLE
Add YouTube video comments scrapper

### ISSUE THREAD

**Issue by Tvax** [TeamNewPipe/NewPipeExtractor#95]
As I understand it, the comments are not loaded directly you have to scroll down to see/fetch them, or you could do it by using this prefix: `https://www.youtube.com/all_comments?v={youtube_id}` 
That's how it's done in Python: [youtube-comment-downloader](https://github.com/egbertbouman/youtube-comment-downloader)

It's something that a lot of users are asking for in the NewPipe Android app, if someone is willing to find a way to scrape the comment section of a video that'd be awesome, and greatly appreciated!

**Comment by theScrabi** [comment]
Verry nice :) ... help is always welcome.

**Comment by elvinup** [comment]
Thanks for pointing that script out @Tvax. I've started playing with it today and got it to give me the **likes** of each comment and was able to group messages by **thread**. https://github.com/elvinup/youtube-comment-downloader
Anything else to scrape that ya'll think newPipe might need?

**Comment by Tvax** [comment]
Ho thank you! I can't test it right now, but what do you mean by threads? The replies of a comment? If so, I can't think of anything else!
We still need to convert it to Java, but great work!

**Comment by elvinup** [comment]
Yep, replies of comments. Before it was just a string of comments. And yea I might try converting it to Java so the project can use it sometime this weekend or next week

**Comment by Tvax** [comment]
Cool! Well done dude!

**Comment by elvinup** [comment]
Alright so I attempted a request similar to what that python repo does, and everything in my request appears to be the same, yet I get a 403 forbidden error back from youtube. I don't know if this is a Java issue or I'm just bad with rest API's.

If someone can figure out how I can make the request without an error (For me its postReq() in CommentScraper.java). I can do the rest with extracting the comments and grouping them by threads and will make a pull request for the extractor.  

https://github.com/elvinup/youtube-comment-downloader/tree/master/JavaEdition/CommentScraper/src

**Comment by theScrabi** [comment]
@elvinup please also keep the Extractor architecture in mind: https://teamnewpipe.github.io/documentation/01_Concept_of_the_extractor/

**Comment by briansaturnino** [comment]
I'm not much of a tech-savvy person relative to you folks. How can I install this? Thank you.

https://github.com/TeamNewPipe/NewPipe/issues/579

**Comment by FlorianSteenbuck** [comment]
@briansaturnino 
**We do not support custom builds we want that features got reviewed and somehow stable before we release a new app**
You need to install:

 - [Java JDK 8](https://docs.oracle.com/javase/8/docs/technotes/guides/install/install_overview.html)
 - [Java JRE 8](https://docs.oracle.com/javase/8/docs/technotes/guides/install/install_overview.html)
 - Git ([linux](https://gist.github.com/derhuerst/1b15ff4652a867391f03#file-linux-md), [mac](https://gist.github.com/derhuerst/1b15ff4652a867391f03#file-mac-md), [windows](https://github.com/git-for-windows/git/releases/latest))

Now we need the source code. This can be complicated for certain features that are based on the NewPipeExtractor. In this case the current change request from @yausername depending on a build able repo that the dev own. So their is no problem with this, but do not blame if this get changed.

Open You Terminal (On Windows Win+R, type cmd, Press Enter)
```bash
git clone https://github.com/TeamNewPipe/NewPipe.git
cd NewPipe
```
Now before we start building this custom build we need the Android SDK, but before you install it with Android Studio their is currently a better way to install only the Android SDK:

- Create a directory somewhere
- Create in this directory the directories `build-tools` and `platforms`
- Create a directory with the name `27.0.3` in `build-tools`
- Download https://dl.google.com/android/repository/platform-27_r03.zip
- Extract `platform-27_r03.zip` and copy directory `android-8.1.0` in the root of `platforms`
- Download:
- For Linux: https://dl-ssl.google.com/android/repository/build-tools_r27.0.3-linux.zip
- For Mac: https://dl-ssl.google.com/android/repository/build-tools_r27.0.3-macosx.zip
- For Windows: https://dl-ssl.google.com/android/repository/build-tools_r27.0.3-windows.zip
- Extract `build-tools_r27.0.3-[windows|macosx|linux].zip` and move the content of the directory `android-8.1.0` to the root of `27.0.3`

Now we need to checkout the changes for the feature.
```bash
git checkout dev
git fetch origin pull/1650/head
```
And final we can build the app with the feature:

Replace $SDK with the absolute path to the directory that you create in the beginning.

Linux/Mac
```bash
export ANDROID_HOME="$SDK"
./gradlew build
```
Windows
```bash
set ANDROID_HOME="$SDK"
gradlew.bat build
```

After this process is done and the build process ends with the message:
```bash
BUILD SUCCESSFUL
```
You can find a unsigned apk for release in `app/build/outputs/apk/release/` and for debug in `app/build/outputs/apk/debug/`

**I only tested this on linux maybe their are something more you need to do on mac or windows.**

**Comment by theScrabi** [comment]
Guys @yausername already works on [this](https://github.com/TeamNewPipe/NewPipeExtractor/pull/101).

**Comment by wb9688** [comment]
Getting top-level comments is already possible in NewPipe for some time. It uses the mobile site though, and I want to reimplement it using YouTube's new site, plus we should also add support for child comments.

**Comment by PeterHindes** [comment]
@briansaturnino You just need to download the source and open the extracted folder in android studio if you want to test the changes early. You will also have to connect your phone with adb debugging if you dont want to use the emulator. This should be enough info for you to start figuring out what you need to do.

**Comment by LostWanita21** [comment]
You can currently view comments on Newpipe, but if that comment has any replies, those will not show up, no option to show replies or anything, so if I comment on a video with an old YT account, get some replies and view the Video in newpipe, only my original comment will show up, no replies and no option to bring them down.

Is it just not implemented or is it one of those that's just impossible
