### ISSUE TITLE
Subscriptions fail to update

### ISSUE THREAD

**Issue by GonzoVF** [TeamNewPipe/NewPipeExtractor#963]
DISCLAIMER: This might be more proper to post on the Newpipe frontend project, but I was not allowed to post a bug report there, so I hope this makes sense here as well, since it could very well be an issue on the backend.

**Steps to Reproduce**
- Open subscription feed
- Swipe down to refresh
- See bug

**Expected Behavior**
- Same videos appear where they were
- You can scroll up to find new videos

**Current Behavior**
- Same videos show up, no updates, regardless of the fact that my subscribed channels have demonstrably uploaded new content

**Device**
- Pixel 3 XL running CalyxOS 3.9.0 (Android 12)

![Screenshot_20221103-002552](https://user-images.githubusercontent.com/31936697/199643023-c387434d-6294-4ecf-992d-2db078a2e483.png)
![Screenshot_20221103-002555](https://user-images.githubusercontent.com/31936697/199643043-5cbd775e-7b10-4752-8db4-68d7c5c3b875.png)
![Screenshot_20221103-002559](https://user-images.githubusercontent.com/31936697/199643065-321fdd17-2597-4d9e-bff0-a371bf0a175f.png)

This example is shown with a subdivided list of subscriptions, but all my subscription lists (including the one with my entire sub feed) behave exactly the same way.

I apologize if this project was not the right place to post, but I believe this is a real bug and no open issue resembled it in the other project

**Comment by GonzoVF** [comment]
Here is proof that the channels have uploaded videos since, if you look at the pictures above and see the 2nd video by Pleasantkenobi, it was uploaded 5 days ago.

He uploads fairly regularly, here are some videos that show up if you look him up directly, notice the upload dates:

**Comment by maxammann** [comment]
I can confirm this issue. Already reinstalled NewPipe.
