### ISSUE TITLE
Subscriptions are not updated

### ISSUE THREAD

**Issue by stemy2** [TeamNewPipe/NewPipeExtractor#966]
Hello,

Since 3 days, theres no new videos in my subscriptions list, even if the youtubers i subscribed have actually released new videos since then. I'm using another youtube app with the exact same subscription list, and 9 videos from my subscription are missing in newpipe compared to the other app.

**Comment by hummelriegel** [comment]
I have the same issue and it seems that the app cannot extract videos from individual channels. It works for the trending videos though.
Could be that it is related to the latest changes that allow an optional alias for any account?

**Comment by estradanic** [comment]
@AudricV could you please comment on why you are closing these issues? Are they supposed to be on the app repo? Can you not reproduce the issue? Are they duplicates?

**Comment by AudricV** [comment]
This issue is invalid, as it this is about the NewPipe app, and not its extractor. This issue is already fixed in the extractor and a release candidate with this fix is already available.
