### ISSUE TITLE
Google Api Issues

### ISSUE THREAD

**Issue by shl0255** [TeamNewPipe/NewPipeExtractor#970]
This week, I imported New pipe Extractor library in my android project
to analyse youtube shared link. When I submit my APK  on the Google
play store. I got a security issue -- GCP Api key exposed in  the
YoutubeParsingHelper.class. Have you met this before? Do you have some
solutions to avoid this issue?  This is my implementation version:
com.github.TeamNewPipe:NewPipeExtractor:9ffdd0948b2ecd82655f5ff2a3e127b2b7695d5b. I have emailed to your team listed on New pipe website.

**Comment by FireMasterK** [comment]
I'm pretty sure using NewPipeExtractor in an app violates Google Play's terms of service.

**Comment by theScrabi** [comment]
We warn for this in the readme.md of the original app. 

Please also be aware if you publish apps using the NewPipeExtractor but don't release the sourcecode of your app you violate our licencing.
