### ISSUE TITLE
No youtube streams on What's new and channel pages

### ISSUE THREAD

**Issue by Afaren57** [TeamNewPipe/NewPipeExtractor#982]
Hello, this is my first time creating an issue, so tell me if I did anything wrong. I post it here because I think it's more related to the extraction of youtube datas than the app itself.

Since last update of NewPipe (v 0.24.1) that correctected the extractions of videos from the new youtube design, videos that came from live doesn't appear like before on the What's new page and the channel page of a youtuber. By the meantime, they do appear when you search for the specific youtuber. Here are some screenshots of the issue.

![Screenshot_2022-11-24-08-26-58-06_ee8807d2de22f1831269d80920e33a3b](https://user-images.githubusercontent.com/58276356/203757958-3f334dbf-b784-4511-a498-8e00fa3ac2fa.jpg)
![Screenshot_2022-11-24-08-27-38-87_fd7367fd0afc7e864f00091a00b3d0b0](https://user-images.githubusercontent.com/58276356/203757963-b083cc10-1b24-47c7-aa3a-b5c3acf3834f.jpg)
![Screenshot_2022-11-24-08-27-48-00_ee8807d2de22f1831269d80920e33a3b](https://user-images.githubusercontent.com/58276356/203757967-a089f5c6-6f45-4168-b0c7-75d814bfd357.jpg)

Last month they were correctly showed, I think this is related to videos not showing in the video tab from the new youtube interface but in the stream one.

**Comment by opusforlife2** [comment]
Wrong repo as well.
